# #####################################################################################
#
# SYSTEM - Snapshot
#
# #####################################################################################
# System - Window Cam Snapshot on Motion
# ##################################
- alias: system_window_snapshot
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.unifi_motion_window
      from: 'off'
      to: 'on'
  action:
#    - delay: '00:00:01'
#    - service: camera.snapshot
#      data:
#        entity_id: camera.uvc_g3_flex_window
#        filename: "/config/www/cam_captures/window.jpg"
    - delay: '00:00:01'
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "{{states('sensor.time')}} {{states('sensor.date')}}"
        data:
          photo:
          #- file: "/config/www/cam_captures/window.jpg"
          - url: http://192.168.1.14:8123{{state_attr('camera.uvc_g3_flex_window','entity_picture')}}
            caption: "{{states('sensor.time')}} {{states('sensor.date')}}"

# ##################################
# System - Dixy Cam Snapshot on Motion
# ##################################
- alias: system_dixy_snapshot
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.unifi_motion_dixy
      from: 'off'
      to: 'on'
  action:
#    - delay: '00:00:01'
#    - service: camera.snapshot
#      data:
#        entity_id: camera.uvc_g3_flex_dixy
#        filename: "/config/www/cam_captures/dixy.jpg"
    - delay: '00:00:01'
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "{{states('sensor.time')}} {{states('sensor.date')}}"
        data:
          photo:
          #- file: "/config/www/cam_captures/dixy.jpg"
          - url: http://192.168.1.14:8123{{state_attr('camera.uvc_g3_flex_dixy','entity_picture')}}
            caption: "{{states('sensor.time')}} {{states('sensor.date')}}"
