# #####################################################################################
#
# VOVA - General
#
# #####################################################################################
# Vova - Sockets On
# ##################################
- alias: vova_sockets_on
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d000236bb94
  condition:
      - condition: state
        entity_id: switch.plug_158d000290a093
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.plug_158d000290a093
        - switch.plug_158d000290a0bc
        - switch.plug_158d000344998e
        - switch.0x00158d0003600ea4_switch #switch.plug_158d0003600ea4
    #- service: homeassistant.turn_on
    #  entity_id: automation.vova_iconbit_check

# ##################################
# Vova - Iconbit Off with TV Off
# ##################################
- alias: vova_tv_box_off_tv_off_iconbit
  initial_state: 'false'
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
      - condition: state
        entity_id: binary_sensor.h96_v
        state: 'on'
      - condition: state
        entity_id: binary_sensor.tv_v
        state: 'off'
        for:
          minutes: 1
  action:
    - service: script.turn_on
      entity_id: script.iconbit_toggle

# ##################################
# Vova - TV Box Off with TV Off
# ##################################
- alias: vova_tv_box_off_tv_off_kodi
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
      - condition: state
        entity_id: binary_sensor.h96_v
        state: 'on'
      - condition: state
        entity_id: binary_sensor.tv_v
        state: 'off'
        for:
          minutes: 2
  action:
    - service: script.turn_on
      entity_id: script.kodi_v_toggle

# ##################################
# Vova - Iconbit Restart
# ##################################
- alias: vova_iconbit_restart
  initial_state: 'false'
  trigger:
    platform: state
    entity_id: binary_sensor.tv_v
    to: 'off'
    for:
      minutes: 10
  condition:
      - condition: state
        entity_id: binary_sensor.iconbit
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.plug_158d000290a0bc
    - delay: '00:02:00'
    - service: switch.turn_on
      entity_id: switch.plug_158d000290a0bc

# ##################################
# Vova - Night mode
# ##################################
- alias: vova_night_mode
  initial_state: 'true'
  trigger:
    platform: time
    at: '23:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.plug_158d00028b4fc3, switch.wall_plug_158d000246776f
      
# ##################################
# Vova - Day mode
# ##################################
- alias: vova_day_mode
  initial_state: 'false'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      #- sat
      #- sun
  action:
    - service: homeassistant.turn_on
      entity_id: switch.plug_158d00028b4fc3 #, switch.wall_plug_158d000246776f

# ##################################
# Vova - Day mode - weekends
# ##################################
- alias: vova_day_mode_we
  initial_state: 'true'
  trigger:
    platform: time
    at: '10:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: homeassistant.turn_on
      entity_id: switch.plug_158d00028b4fc3 #, switch.wall_plug_158d000246776f

