homeassistant:
  name: Dima's Home_Main Server
  latitude: !secret lat
  longitude: !secret long
  elevation: 172
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include my_config/customize.yaml
  customize_glob: !include my_config/customize_glob.yaml
#  customize_domain:
#    automation: 
#      initial_state: 'on'
  auth_providers:
  - type: trusted_networks
    trusted_networks:
      - 172.30.32.0/24
      - 172.30.31.0/24
      - 172.30.33.0/24
      - 172.17.0.0/16
      - 192.168.1.0/24
    allow_bypass_login: true
  - type: homeassistant
#  - type: legacy_api_password
#    api_password: !secret http_passwprd
  whitelist_external_dirs:
      - /config
      - /tmp
      - /share

api:

http:
  #api_password: !secret http_passwprd
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  ip_ban_enabled: true
  login_attempts_threshold: 5

automation: !include_dir_merge_list my_config/automation
sensor: !include_dir_merge_list my_config/sensors
script: !include_dir_merge_named my_config/scripts
binary_sensor: !include_dir_merge_list my_config/bi-sensor

timer: !include my_config/timer.yaml
device_tracker: !include my_config/device_tracker.yaml
input_number: !include my_config/input_number.yaml
group: !include my_config/groups.yaml
zone: !include my_config/zone.yaml
switch: !include my_config/switch.yaml
counter: !include my_config/counter.yaml
light: !include my_config/light.yaml
yeelight: !include my_config/yeelight.yaml
fan: !include my_config/fan.yaml
xiaomi_aqara: !include my_config/gateways.yaml
person: !include my_config/person.yaml
camera: !include my_config/camera.yaml
notify: !include my_config/notify.yaml
custom_updater: !include my_config/custom_updater.yaml
recorder: !include my_config/recorder.yaml
telegram_bot: !include my_config/telegram_bot.yaml
weather: !include my_config/weather.yaml
input_select: !include my_config/input_select.yaml
input_boolean: !include my_config/input_boolean.yaml
transmission: !include my_config/transmission.yaml
tts: !include my_config/tts.yaml
remote: !include my_config/remote.yaml
panel_iframe: !include my_config/panel_iframe.yaml
proximity: !include my_config/proximity.yaml

#hacs:
#  token: !secret github_access_token

# history_graph: !include history_graph.yaml
mobile_app:
system_health:
cloud:
config:
hassio:
wake_on_lan:
discovery:
conversation:
history:
logbook:
map:
sun:
ffmpeg:
ios:

#adguard:
#  host: 192.168.1.14
#  port: 800
#  username: !secret adguard_user
#  password: !secret adguard_pass
#  monitored_conditions:
#    - blocked
#    - blocked_percentage
#    - queries
  
speedtestdotnet:
  #server_id: 3682
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

#air_quality:
#  - platform: opensensemap
#    station_id: 5c6409daa100840019d4d0bf

system_log:
  fire_event: true
  max_entries: 25
  
frontend:
  themes: !include_dir_merge_named my_config/themes
  javascript_version: latest
  
lovelace:
  mode: yaml

updater:
  include_used_components: true

logger:
  default: info
  #logs:
  #  homeassistant.components.switch.xiaomi_miio: debug
  #  miio: debug 
  #logs:
  #  xiaomi_gateway: debug

#twilio:
#  account_sid: !secret twilio_account_sid
#  auth_token: !secret twilio_auth_token

media_player:
  - platform: mpd
    host: 192.168.1.14
    port: 6600
    name: MPD
  - platform: mpd
    host: 192.168.1.57
    port: 6600
    name: MPD_RPI
  - platform: mpd
    host: 192.168.1.60
    port: 6600
    name: MPD_j3455
  

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

rest_command:
  google_backup:
    url: 'http://192.168.1.14:8055/gb/doBackup'
    timeout: '300'

#mqtt:
#  discovery: true
#  birth_message:
#    topic: 'hass/status'
#    payload: 'online'
#  will_message:
#    topic: 'hass/status'
#    payload: 'offline'

#influxdb:
#  host: !secret influxdb_host
#  port: !secret influxdb_port
#  database: !secret influxdb_database
#  username: !secret influxdb_username
#  password: !secret influxdb_password
#  max_retries: 3
#  default_measurement: state
