homeassistant:
  name: Dima's Home_Main Server
  external_url: !secret main_external_url
  internal_url: !secret main_internal_url
  latitude: !secret lat
  longitude: !secret long
  elevation: 172
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Moscow
  customize: !include my_config/customize.yaml
  customize_glob: !include my_config/customize_glob.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.30.31.0/24
        - 172.30.33.0/24
        - 172.17.0.0/16
        - 192.168.1.0/24
      allow_bypass_login: true
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret api_password
  whitelist_external_dirs:
      - /config
      - /tmp
      - /share

api:

stream:

circadian_lighting:
  max_colortemp: 5500 
  min_colortemp: 3000
  interval: 300
  transition: 60

mqtt:
  broker: 192.168.1.30
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant
  client_id: main_ha
  birth_message:
    topic: 'servers/main'
    payload: 'online'
  will_message:
    topic: 'servers/main'
    payload: 'offline'

http:
  #base_url: !secret main_base_url
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  ip_ban_enabled: false
  login_attempts_threshold: 5

automation: !include_dir_merge_list my_config/automation
sensor: !include_dir_merge_list my_config/sensors
switch: !include_dir_merge_list my_config/switch
binary_sensor: !include_dir_merge_list my_config/bi-sensor
script: !include_dir_merge_named my_config/scripts

lovelace: !include my_config/lovelace.yaml
timer: !include my_config/timer.yaml
device_tracker: !include my_config/device_tracker.yaml
input_number: !include my_config/input_number.yaml
input_text: !include my_config/input_text.yaml
group: !include my_config/groups.yaml
zone: !include my_config/zone.yaml
counter: !include my_config/counter.yaml
light: !include my_config/light.yaml
yeelight: !include my_config/yeelight.yaml
fan: !include my_config/fan.yaml
xiaomi_aqara: !include my_config/gateways.yaml
person: !include my_config/person.yaml
camera: !include my_config/camera.yaml
notify: !include my_config/notify.yaml
scene: !include my_config/scene.yaml
shell_command: !include my_config/shell_command.yaml

#custom_updater: !include my_config/custom_updater.yaml

recorder: !include my_config/recorder.yaml
history: !include my_config/history.yaml
logbook: !include my_config/logbook.yaml

telegram_bot: !include my_config/telegram_bot.yaml
weather: !include my_config/weather.yaml
input_select: !include my_config/input_select.yaml
input_boolean: !include my_config/input_boolean.yaml
input_datetime: !include my_config/input_datetime.yaml
transmission: !include my_config/transmission.yaml
tts: !include my_config/tts.yaml
remote: !include my_config/remote.yaml
panel_iframe: !include my_config/panel_iframe.yaml
proximity: !include my_config/proximity.yaml

utility_meter: !include my_config/utility_meter.yaml

# sonoff:
#   username: !secret sonoff_user
#   password: !secret sonoff_password
#   reload: always
#   devices:
#     1000d03987:
#       device_class: [switch]

discovery:
  ignore:
    - xiaomi_gw
    - yeelight
zeroconf:
ssdp:

hacs:
  token: !secret github_access_token

# history_graph: !include history_graph.yaml
mobile_app:
system_health:
#cloud:
config:
hassio:
wake_on_lan:
conversation:
map:
sun:
ios:
  push:
    categories:
      - name: Domofon
        identifier: 'domofon_call'
        actions:
          - identifier: 'DOMOFON_OPEN_DOOR'
            title: 'Открыть дверь'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'DOMOFON_DONOTOPEN_DOOR'
            title: 'Игнорировать'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# cast:
#   media_player:
#     - host: 192.168.1.45
#     - host: 192.168.1.46
#     - host: 192.168.1.47
#     - host: 192.168.1.48
#     - host: 192.168.1.49
    
#adguard:
#  host: 192.168.1.14
#  port: 800
#  username: !secret adguard_user
#  password: !secret adguard_pass
#  monitored_conditions:
#    - blocked
#    - blocked_percentage
#    - queries
  
speedtestdotnet:
  scan_interval:
    minutes: 120
  monitored_conditions:
    - ping
    - download
    - upload

system_log:
  fire_event: true
#  max_entries: 25
  
frontend:
  themes: !include_dir_merge_named themes
#  javascript_version: latest
  
updater:
  include_used_components: true

logger:
  default: info

#  logs:
#    homeassistant.components.sensor.rest: fatal
#  logs:
#    xiaomi_gateway: debug

rest_command:
  kiosk_command:
    url: !secret rest_url_kiosk_command
  kiosk_restart:
    url: !secret rest_kiosk_restart

start_time:
    
  #logs:
  #  homeassistant.components.switch.xiaomi_miio: debug
  #  miio: debug 
  #logs:
  #  yeelight: debug
  #  xiaomi_gateway: debug
  
  # default: warning
  # logs:
  #   xiaomi_gateway: fatal
  #   miio.device: fatal
  #   homeassistant.components.xiaomi_miio.switch: error
  #   homeassistant.components.template.sensor: fatal
  #   homeassistant.components.binary_sensor: error
  #   homeassistant.components.mgtt: error
  #   homeassistant.components: warning
  #   homeassistant.components.switch: error
  #   homeassistant.components.fan: error
  #   homeassistant.components.sensor: error
  #   homeassistant.components.mitemp_bt.sensor: critical
  #   homeassistant.helpers.entity: fatal
  #   homeassistant.helpers.condition: error
  #   homeassistant.loader: error
  #   homeassistant.setup: error
  #   homeassistant.components.device_tracker: error
  #   homeassistant.components.light: error
  #   telegram.vendor.ptb_urllib3.urllib3.connectionpool: error
  #   telegram.ext.updater: fatal
  #   pychromecast.socket_client: fatal
  #   homeassistant.components.xiaomi_miio.fan: fatal  

#twilio:
#  account_sid: !secret twilio_account_sid
#  auth_token: !secret twilio_auth_token

#browser_mod:
#  devices:
#    8798b8fb_99f76b42:
#      name: m6800
#      camera: true
#    a3b55e6b_a294e212:
#      name: Digma_8027
#      camera: true

media_player: !include my_config/media_player.yaml
  
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

life360:
  interval_seconds: 10
  show_as_state:
    - driving
    - moving
#  driving_speed: 1000
#  max_gps_accuracy: 100
#  max_update_wait:
#    minutes: 45

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

z2m_light_admin:

# image_processing:
#   - platform: tensorflow
#     scan_interval: 99999
#     source:
#       - entity_id: camera.local_file_entr
#       - entity_id: camera.local_file_entr2
#       - entity_id: camera.local_file_hall
#     model:
#       graph: tensorflow/frozen_inference_graph.pb

# monitor_docker:
#   name: Docker
#   url: unix:///var/run/docker.sock