homeassistant:
  name: Dima's Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 172
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include my_config/customize.yaml
  customize_glob: !include my_config/customize_glob.yaml
#  customize_domain:
#    automation:
#      initial_state: 'on'
  auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
  #    - 172.30.0.0/23
  #    - 172.17.0.0/16
      - 192.168.1.0/24
  - type: legacy_api_password
    api_password: !secret apipass
  whitelist_external_dirs:
      - /config
      - /tmp
      - /share

automation: !include_dir_merge_list my_config/automation
sensor: !include_dir_merge_list my_config/sensors
      
script: !include my_config/scripts.yaml
timer: !include my_config/timer.yaml
binary_sensor: !include my_config/bi-sensor.yaml
device_tracker: !include my_config/device_tracker.yaml
input_number: !include my_config/input_number.yaml
group: !include my_config/groups.yaml
zone: !include my_config/zone.yaml
switch: !include my_config/switch.yaml
counter: !include my_config/counter.yaml
light: !include my_config/light.yaml
yeelight: !include my_config/yeelight.yaml
fan: !include my_config/fan.yaml
xiaomi_aqara: !include my_config/gateways.yaml
person: !include my_config/person.yaml
camera: !include my_config/camera.yaml
notify: !include my_config/notify.yaml
custom_updater: !include my_config/custom_updater.yaml
recorder: !include my_config/recorder.yaml
telegram_bot: !include my_config/telegram_bot.yaml
weather: !include my_config/weather.yaml
input_select: !include my_config/input_select.yaml
input_boolean: !include my_config/input_boolean.yaml
transmission: !include my_config/transmission.yaml
tts: !include my_config/tts.yaml
remote: !include my_config/remote.yaml
panel_iframe: !include my_config/panel_iframe.yaml


# history_graph: !include history_graph.yaml

system_health:
cloud:
config:
hassio:
wake_on_lan:
discovery:
conversation:
history:
logbook:
map:
sun:
ffmpeg:
ios:

#homekit:
#  auto_start: False
#  filter:
#    include_domains:
      #- device_tracker
#      - switch
      #- binary_sensor
#      - light
#      - media_player
      #- sensor
      #- fan


speedtestdotnet:
  #server_id: 3682
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
    

system_log:
  fire_event: true
  
#image_processing:
#  - platform: facebox
#    ip_address: 192.168.1.14
#    port: 8080
#    source:
#      - entity_id: camera.uvc_g3_flex_kitchen
#        name: kitchen
#      - entity_id: camera.uvc_g3_flex_hall
#        name: hall
#      - entity_id: camera.uvc_g3_flex_entrance
#        name: entrance
      #- entity_id: camera.hall_saved_image
      #  name: hall_saved_image
      #- entity_id: camera.entrance_saved_image
      #  name: entrance_saved_image
        
frontend:
  themes: !include_dir_merge_named my_config/themes
  javascript_version: latest
  
lovelace:
  mode: yaml

updater:
  include_used_components: true

logger:
  default: info
  #logs:
  #  xiaomi_gateway: debug

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

media_player:
  - platform: mpd
    host: 192.168.1.14
    port: 6600
    name: MPD
  
#cast:
#  media_player:
#    - host: 192.168.1.45
#    - host: 192.168.1.46
#    - host: 192.168.1.47
#    - host: 192.168.1.48

#googlehome:
#  devices:
#    - host: 192.168.1.45
#    - host: 192.168.1.46
#    - host: 192.168.1.47
#    - host: 192.168.1.48
    
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# Google Drive Backup
rest_command:
  google_backup:
    url: 'http://192.168.1.14:8055/gb/doBackup'
    timeout: '300'

http:
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  ip_ban_enabled: true
  login_attempts_threshold: 5

#influxdb:
#  host: !secret influxdb_host
#  port: !secret influxdb_port
#  database: !secret influxdb_database
#  username: !secret influxdb_username
#  password: !secret influxdb_password
#  max_retries: 3
#  default_measurement: state
