resources:
  - url: /local/bar-card.js
    type: js
  - url: /local/custom-weather-card-chart.js
    type: module
  - url: /local/mini-graph-card-bundle.js
    type: module
  - url: /local/tracker-card.js?track=true
    type: module
  - url: /local/vertical-stack-in-card.js?v=v0.1.1
    type: js
  - url: /local/battery-entity.js?v=0.2
    type: module


title: Home
views:
  - !include my_config/lovelace/01_main.yaml
  - !include my_config/lovelace/02_security.yaml
  - !include my_config/lovelace/03_devices_by_rooms.yaml
  - !include my_config/lovelace/04_sensors_by_rooms.yaml
  - !include my_config/lovelace/05_utility_counters.yaml
  - !include my_config/lovelace/06_sockets_load.yaml
  - !include my_config/lovelace/07_device_trackers.yaml
  - !include my_config/lovelace/08_cctv.yaml
  - !include my_config/lovelace/09_climate.yaml
  - !include my_config/lovelace/10_system_status.yaml
  - !include my_config/lovelace/11_pihole.yaml
  - !include my_config/lovelace/12_batteries.yaml