# ############################################################################
# Security 
# ############################################################################
  - platform: template
    sensors:
    
      security:
        friendly_name: Security mode
        value_template: "{{ is_state('input_boolean.security_mode', 'on') }}"
        icon_template: >
          {% if is_state('input_boolean.security_mode', 'on') %}
            mdi:shield
          {% elif is_state('input_boolean.security_mode', 'off') %}
            mdi:shield-off
          {% endif %}
      
      motion_internal:
        friendly_name: Motion Internal
        value_template: "{{ is_state('group.motioninternal','on') }}"
      
      motion:
        friendly_name: Motion
        value_template: "{{ is_state('group.motion','on') }}"
        #icon_template: >-
        #  {%if states.group.motion.state == 'on' %}
        #  mdi:run
        #  {% else %}
        #  mdi:walk
        #  {% endif %}
    
      motion_unifi:
        friendly_name: Motion Unifi
        value_template: "{{ is_state('group.motionunifi','on') }}"
        #icon_template: >-
        #  {%if states.group.motionunifi.state == 'on' %}
        #  mdi:run
        #  {% else %}
        #  mdi:walk
        #  {% endif %}
      
      doors:
        friendly_name: Doors
        value_template: "{{ is_state('group.doors','on') }}"
        #icon_template: >-
        #  {%if states.group.doors.state == 'on' %}
        #  mdi:door-open
        #  {% else %}
         # mdi:door-closed
        #  {% endif %}

      windows:
        friendly_name: Windows
        value_template: "{{ is_state('group.windows','on') }}"
        #icon_template: >-
        #  {%if states.group.windows.state == 'on' %}
        #  mdi:window-open
        #  {% else %}
        #  mdi:window-closed
        #  {% endif %}