# #####################################################################################
#
# STORAGE - Light
#
# #####################################################################################
# Storage - Auto Light On
# ##################################
- alias: storage_auto_light_on
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.motion
    #   event_data:
    #     entity_id: binary_sensor.motion_sensor_158d0001aea602
    - platform: state
      entity_id: binary_sensor.0x00158d0001aea602_occupancy
      from: 'off'
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d0002a36433_switch_right #switch.0x00158d000248bf53_switch #switch.wall_switch_158d000248bf53

# ##################################
# Storage - Auto Light Off
# ##################################
- alias: storage_light_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.main_light_st
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d0002a36433_switch_right, switch.0x00158d0002a36433_switch_left #switch.0x00158d000248bf53_switch #switch.wall_switch_158d000248bf53
    - service: timer.cancel
      entity_id: timer.main_light_st

# ##################################
# Storage - Timer Start
# ##################################
- alias: storage_timer_start
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x00158d0002a36433_switch_right, switch.0x00158d0002a36433_switch_left #switch.0x00158d000248bf53_switch #switch.wall_switch_158d000248bf53
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_st
    - service: timer.start
      entity_id: timer.main_light_st

# ##################################
# Storage - Timer restart with movement
# ################################## 
- alias: storage_timer_restart
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.motion
    #   event_data:
    #     entity_id:  binary_sensor.motion_sensor_158d0001aea602
    - platform: state
      entity_id: binary_sensor.0x00158d0001aea602_occupancy
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.0x00158d0002a36433_switch_right
        state: 'on'
      - condition: state
        entity_id: switch.0x00158d0002a36433_switch_left
        state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_st
    - service: timer.start
      entity_id: timer.main_light_st

# ##################################
# Storage - Timer off
# ################################## 
- alias: storage_timer_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x00158d0002a36433_switch_right, switch.0x00158d0002a36433_switch_left #switch.0x00158d000248bf53_switch #switch.wall_switch_158d000248bf53
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_st
    - service: automation.turn_off
      entity_id: automation.storage_auto_light_on
    - delay: '00:00:10'
    - service: automation.turn_on
      entity_id: automation.storage_auto_light_on

# ##################################
# Storage - Night Off
# ##################################
- alias: storage_night_off
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d00023d0b86
    #     click_type: single
    - platform: state
      entity_id: sensor.0x00158d00023d0b86_click
      to: 'single'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.0x00158d0001f5501f_switch, switch.0x00158d000216528c_switch, light.gateway_light_7811dcb8cb4b, switch.0x00158d0002a36433_switch_right, switch.0x00158d0002a36433_switch_left, light.led_strip_hb, light.lt11_1_led
      
# ##################################
# Storage - Hall big Light Auto turn off
# ##################################
- alias: storage_light_automations_off
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d00023d0b86
    #     click_type: double
    - platform: state
      entity_id: sensor.0x00158d00023d0b86_click
      to: 'double'
  condition:
    - condition: state
      entity_id: automation.hall_big_auto_light_on
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.hall_big_auto_light_on, automation.hall_big_auto_night_light_on
    # - delay: '01:00:00'
    # - service: homeassistant.turn_on
    #   entity_id: automation.hall_big_auto_light_on, automation.hall_big_auto_night_light_on

# ##################################
# Storage - Hall big Light Auto turn on
# ##################################
- alias: storage_light_automations_on
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d00023d0b86
    #     click_type: single
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d00023d0b86
    #     click_type: double
    - platform: state
      entity_id: sensor.0x00158d00023d0b86_click
      to: 'single'
    - platform: state
      entity_id: sensor.0x00158d00023d0b86_click
      to: 'double'
    - platform: state
      entity_id: switch.0x00158d000223921b_switch_left, switch.0x00158d000223921b_switch_right, switch.0x00158d000253f04a_switch_left, switch.0x00158d000253f04a_switch_right
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: switch.0x00158d000223921b_switch_left, switch.0x00158d000223921b_switch_right, switch.0x00158d000253f04a_switch_left, switch.0x00158d000253f04a_switch_right
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: automation.hall_big_auto_light_on
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: automation.hall_big_auto_light_on, automation.hall_big_auto_night_light_on