# #####################################################################################
#
# BATHROOM
#
# #####################################################################################
# Bathroom Water Valves Test
# ##################################
- alias: bathroom_water_valves_test
  initial_state: 'true'
  trigger:
    - platform: time
      at: '00:01:00'
  condition:
    - condition: time
      weekday:
        - mon
        - fri
  action:
    - service: notify.telegram
      data_template: 
        message: "\U0001f6b0 Проверка кранов - закрываем!"
    - service: switch.turn_off
      entity_id: switch.s26_socket_5_relay
    - service: switch.turn_on
      entity_id: switch.plug_158d00020d8679
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.plug_158d00020d8679
    - delay: '00:00:05'
    - service: notify.telegram
      data_template: 
        message: "\U0001f6b0 Проверка кранов - открываем!"
    - service: switch.turn_on
      entity_id: switch.plug_158d0001f54f90
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.plug_158d0001f54f90
    - service: switch.turn_on
      entity_id: switch.s26_socket_5_relay
    - service: notify.telegram
      data_template: 
        message: "\U00002705 Проверка кранов завершена!"