# #####################################################################################
#
# BATHROOM
#
# #####################################################################################
# Bathroom - Washing Machine Washing
# ##################################
- alias: bathroom_washing_machine_washing
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.washer_b
      from: 'off'
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_uptime
      above: 5
    - condition: state
      entity_id: input_select.washer_state
      state: 'Stopped'
  action:
    - service: timer.cancel
      entity_id: timer.washer_b
    - service: timer.start
      entity_id: timer.washer_b
    - service: input_number.set_value
      data_template:
        entity_id: input_number.washer_start
        value: '{{as_timestamp (now())|int}}'
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_state
        option: Washing
    - service: notify.telegram
      data_template: 
        message: "\U000023F3 Стирка начата!"
 
# ##################################
# Bathroom - Washing Machine Drying
# ##################################
- alias: bathroom_washing_machine_drying
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.washer_b
    to: 'off'
    from: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.0x158d0003262a35_contact
      state: 'off'
    - condition: state
      entity_id: input_select.washer_state
      state: 'Washing'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_state
        option: Drying
    - service: notify.telegram
      data_template: 
        message: "\U0000231B Стирка завершена! Время стирки составило {{ ( (as_timestamp(strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M'))| round(0) - as_timestamp(states.timer.washer_b.last_changed)| int) / 60 )| round(0) }}мин."
    - service: timer.cancel
      entity_id: timer.washer_b
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template: 
        entity_id: media_player.home_mini_k
        message: "Ст+ирка завершен+а! В+ытащите бель+ё пож+алуста!"

# ##################################
# Bathroom - Washing Machine Extract
# ##################################
- alias: bathroom_washing_machine_extract
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d0003262a35_contact
    to: 'on'
    from: 'off'
  condition:
    - condition: state
      entity_id: input_select.washer_state
      state: 'Washing'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_state
        option: Stopped

# ##################################
# Bathroom - Washing Machine Rinsing
# ##################################
- alias: bathroom_washing_machine_rinsing
  initial_state: 'false'
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d0003262a35_contact
    to: 'on'
    from: 'off'
  condition:
    - condition: state
      entity_id: input_select.washer_state
      state: 'Washing'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_state
        option: Stopped

# ##################################
# Bathroom - Washing Machine Add Load
# ##################################
- alias: bathroom_washing_machine_add_load
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d0003262a35_contact
    to: 'off'
    from: 'on'
  condition:
    - condition: state
      entity_id: input_select.washer_state
      state: 'Stopped'
    - condition: state
      entity_id: binary_sensor.washer_b
      state: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_state
        option: Washing 


# ##################################
# Bathroom - Washing Machine Stopped
# ##################################
- alias: bathroom_washing_machine_stopped
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d0003262a35_contact
    to: 'on'
    from: 'off'
  condition:
    - condition: state
      entity_id: input_select.washer_state
      state: 'Drying'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washer_state
        option: Stopped

# ##################################
# Bathroom - Washing Machine Open Door Notification
# ##################################
- alias: bathroom_washing_machine_open_door_after_washing
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/15"
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_uptime
      above: 5
    - condition: state
      entity_id: input_select.washer_state
      state: 'Drying'
    - condition: state
      entity_id: binary_sensor.0x158d0003262a35_contact
      state: 'off'
  action:
    - service: notify.telegram
      data_template: 
        message: "\U0001f4a8 Откройте дверцу стиральной машины!"