  security_mode_toggle:
    alias: Security mode toggle
    sequence:
      - service_template: >
          homeassistant.turn_{%if is_state('input_boolean.security_mode','on') %}off{% else %}on{%endif%}
        entity_id: input_boolean.security_mode, automation.security_sensors_state_change
