# #####################################################################################
#
# TOILET - Light
#
# #####################################################################################
# Toilet - Timer restart with movement
# ################################## 
- alias: toilet_timer_restart
  initial_state: 'true'
  trigger:
#    - platform: event
#      event_type: xiaomi_aqara.motion
#      event_data:
#        entity_id:  binary_sensor.motion_sensor_158d0001e54280
    - platform: state
      entity_id: binary_sensor.0x00158d0001e54280_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.0x00158d0002a36f7f_switch_left #switch.wall_switch_left_158d0002a36f7f
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_t
    - service: timer.start
      entity_id: timer.main_light_t

# ##################################
# Toilet - Timer off
# ################################## 
- alias: toilet_timer_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x00158d0002a36f7f_switch_left #switch.wall_switch_left_158d0002a36f7f
      to: 'off'
      from: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_t
    
# ##################################
# Toilet - Timer start
# ################################## 
- alias: toilet_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x00158d0002a36f7f_switch_left #switch.wall_switch_left_158d0002a36f7f
      to: 'on'
      from: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_t
    - service: timer.start
      entity_id: timer.main_light_t

# ##################################
# Toilet - Timer pause on
# ################################## 
- alias: toilet_timer_pause_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0001e54280_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.0x00158d000232ddd6_contact
      state: 'off'
    - condition: state
      entity_id: switch.0x00158d0002a36f7f_switch_left
      state: 'on'
  action:
    - service: timer.pause
      entity_id: timer.main_light_t
    - service: automation.turn_off
      entity_id: automation.toilet_timer_restart
    
# ##################################
# Bathroom - Timer pause off
# ################################## 
- alias: toilet_timer_pause_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000232ddd6_contact #binary_sensor.door_window_sensor_158d000232ddd6
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.0x00158d0002a36f7f_switch_left #switch.wall_switch_left_158d0002a36f7f
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.main_light_t
    - service: automation.turn_on
      entity_id: automation.toilet_timer_restart
    
# ##################################
# Toilet - Auto Light On
# ##################################
- alias: toilet_auto_light_on
  initial_state: 'true'
  trigger:
#    - platform: event
#      event_type: xiaomi_aqara.motion
#      event_data:
#        entity_id:  binary_sensor.motion_sensor_158d0001e54280
    - platform: state
      entity_id: binary_sensor.0x00158d0001e54280_occupancy
      from: 'off'
      to: 'on'
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d0001b97111
    #     click_type: single
    - platform: state
      entity_id: sensor.0x00158d0001b97111_click
      to: 'single'
    - platform: state
      entity_id: binary_sensor.0x00158d000232ddd6_contact #binary_sensor.door_window_sensor_158d000232ddd6
      to: 'off'
      from: 'on'
  condition:
    - condition: state
      entity_id: switch.0x00158d0002a36f7f_switch_left #switch.wall_switch_left_158d0002a36f7f
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d0002a36f7f_switch_left #switch.wall_switch_left_158d0002a36f7f
    
# ##################################
# Toilet - Auto Light Off
# ##################################
- alias: toilet_auto_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.main_light_t
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d0002a36f7f_switch_left #switch.wall_switch_left_158d0002a36f7f

# ##################################
# Toilet - Auto Light off - No Motion 2m and Cover Closed
# ##################################
- alias: toilet_auto_light_off_no_motion_cover_closed
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0001e54280_occupancy #binary_sensor.motion_sensor_158d0001e54280
      to: 'off'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.0x00158d000232ddd6_contact #binary_sensor.door_window_sensor_158d000232ddd6
        state: 'on'
      - condition: state
        entity_id: switch.0x00158d0002a36f7f_switch_left #switch.wall_switch_left_158d0002a36f7f
        state: 'on'
  action:
    - service: timer.finish
      entity_id: timer.main_light_t

# ##################################
# Toilet - Light Toggle with Repeater
# ##################################
- alias: toilet_light_toggle_repeater
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.wall_switch_right_158d0001e0a622
    - platform: state
      entity_id: sensor.0x00158d0001e0a622_click
      to: 'right'
  action:
    - service: switch.toggle
      entity_id: switch.0x00158d0002a36f7f_switch_left #switch.wall_switch_left_158d0002a36f7f