# ##################################
# Toilet - Air Freshener Counter
# ##################################
- alias: toilet_air_freshener_counter
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.air_freshener_spray
      from: 'on'
      to: 'off'
  action:
    - service: counter.increment
      entity_id: counter.air_freshener_toilet
    - service: input_text.set_value
      data_template:
        entity_id: input_text.air_freshener_last_spray
        value: "{{now().strftime('%d.%m.%Y %H:%M')}}"

# ##################################
# Toilet - Air Freshener Spray
# ##################################
- alias: toilet_air_freshener_spray
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001b97111_action
      to: 'double'
    - platform: state
      entity_id: binary_sensor.toilet_usage
      to: 'on'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: switch.air_freshener_spray
      state: 'off'
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.0x158d000232ddd6_contact
          to: 'on'
          for:
            seconds: 5
    - service: switch.turn_on
      entity_id: switch.air_freshener_spray

# ##################################
# Toilet - Air Freshener Battery Alert
# ##################################
- alias: toilet_air_freshener_battery_alert
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.esp01_air_freshener_vcc
      below: 3
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50b Низкий заряд батареи освежителя {{states('sensor.esp01_air_freshener_vcc')}}!"