# #####################################################################################
#
# MASTER BEDROOM - Lights
#
# #####################################################################################
# MB Table Lamp (Philips E27) Toggle
# ##################################
- alias: master_bedroom_table_lamp_toggle
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d00023d3116_action
      to: 'single'
    - platform: state
      entity_id: sensor.0x158d00013e6aa5_action
      to: 'button_1_single'
  action:
    - service: light.toggle
      entity_id: light.philips_e27_mb
      # data_template:
      #   transition: 1
      #   brightness_pct: >
      #     {%- if is_state('binary_sensor.tod_day','off') -%}
      #     3
      #     {%- else -%}
      #     100
      #     {% endif %}
      #   kelvin: >
      #     {%- if is_state('binary_sensor.tod_day','off') -%}
      #     3000
      #     {%- else -%}
      #     5000
      #     {% endif %}

# # ##################################
# # MB Table Lamp (Philips E27) Toggle Entrance
# # ##################################
# - alias: master_bedroom_table_lamp_toggle_entrance
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: sensor.0x00158d00013e6aa5_click
#       to: 'left'
#   condition:
#     - condition: state
#       entity_id: light.philips_e27_mb
#       state: 'off'
#   action:
#     - choose:
#         - conditions:
#             - condition: state
#               entity_id: binary_sensor.tod_day
#               state: 'on'
#           sequence:
#             - service: light.turn_on
#               data_template:
#                 entity_id: light.philips_e27_mb
#                 scene: 1
#         - conditions:
#             - condition: state
#               entity_id: binary_sensor.tod_day
#               state: 'off'
#           sequence:
#             - service: light.turn_on
#               data_template:
#                 entity_id: light.philips_e27_mb
#                 scene: 4


# ##################################
# Master_bedroom Table Lamp (Philips E27) - Switch to Bright
# ##################################
- alias: master_bedroom_table_lamp_bright
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d00023d3116_action
      to: 'double'
  action:
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_mb
      data:
        scene: 1

# ##################################
# Master_bedroom Table Lamp (Philips E27) - Switch to Mid-Night
# ##################################
- alias: master_bedroom_table_lamp_night
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d00023d3116_action
      to: 'hold'
  action:
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_mb
      data:
        scene: 4

# ##################################        
# Master Bedroom Main Lamp (Xiaomi Round LED) - On
# ##################################
- alias: master_bedroom_main_lamp_on_if_lamp_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d00013e6aa5_action
      to: 'button_2_single'
  condition:
    - condition: state
      entity_id: light.round_led_mb
      state: 'off'    
  action:
    - service: light.turn_on
      entity_id: light.round_led_mb
      data_template:
        brightness_pct: 95
        kelvin: 5000

# ##################################
# Master Bedroom Main Lamp (Xiaomi Round LED) - Off
# ##################################
- alias: master_bedroom_main_lamp_off_if_lamp_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d00013e6aa5_action
      to: 'button_2_single'
  condition:
    - condition: state
      entity_id: light.round_led_mb
      state: 'on'    
  action:
    - service: light.turn_off
      entity_id: light.round_led_mb

# # ##################################
# # Master Bedroom Main Lamp (Xiaomi Round LED) - Brightness change with left button 33%
# # ##################################
# - alias: master_bedroom_main_lamp_on_30_if_lamp_off
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: sensor.0x00158d00013e6aa5_click
#       to: 'left'
#   condition:
#     - condition: state
#       entity_id: light.round_led_mb
#       state: 'off'    
#   action:
#     - service: light.turn_on
#       entity_id: light.round_led_mb
#       data_template:
#         brightness_pct: 5
#         kelvin: 3000
      
# # ##################################
# # Master Bedroom Main Lamp (Xiaomi Round LED) - Turn Off with Left Button
# # ##################################
# - alias: master_bedroom_main_lamp_off_if_lamp_on_with_left_button
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: sensor.0x00158d00013e6aa5_click
#       to: 'left'
#   condition:
#     - condition: state
#       entity_id: light.round_led_mb
#       state: 'on'
#   action:
#     - service: light.turn_off
#       entity_id: light.round_led_mb
    
# ##################################
# Master Bedroom - Round LED Reset 
# ##################################
- alias: master_bedroom_round_led_reset
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: light.round_led_mb
      state: 'unavailable'
      for:
        minutes: 2
  action:
    - service: script.turn_on
      entity_id: script.round_led_mb_restart

# ##################################
# Master Bedroom - Turn Lamp Switch On if Off
# ##################################
- alias: master_bedroom_main_lamp_switch_on_if_off
  initial_state: 'true'
  trigger:
    # - platform: state
    #   entity_id: sensor.0x00158d00013e6aa5_click
    #   to: 'left'
    - platform: state
      entity_id: sensor.0x158d00013e6aa5_action
      to: 'button_2_single'
  condition:
    condition: state
    entity_id: switch.sonoff_basic_3_relay
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.sonoff_basic_3_relay

# # ##################################
# # Master Bedroom - Timer restart with movement
# # ################################## 
# - alias: master_bedroom_timer_restart
#   initial_state: 'true'
#   trigger:
#     - platform: event
#       event_type: xiaomi_aqara.motion
#       event_data:
#         entity_id: binary_sensor.motion_sensor_158d0001e53cda
#   condition:
#     - condition: state
#       entity_id: light.round_led_mb
#       state: 'on'
#   action:
#   - service: timer.cancel
#     entity_id: timer.main_light_mb
#   - service: timer.start
#     entity_id: timer.main_light_mb

# # ##################################
# # Master Bedroom - Timer off
# # ################################## 
# - alias: master_bedroom_timer_off
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: light.round_led_mb
#       to: 'off'
#       from: 'on'
#   action:
#     - service: timer.cancel
#       entity_id: timer.main_light_mb
#     - service: automation.turn_off
#       entity_id: automation.master_bedroom_auto_light_on
#     - delay: '00:00:10'
#     - service: automation.turn_on
#       entity_id: automation.master_bedroom_auto_light_on

# # ##################################
# # Master Bedroom - Timer start on light on
# # ################################## 
# - alias: master_bedroom_timer_on
#   initial_state: 'true'
#   trigger:
#   - platform: state
#     entity_id: light.round_led_mb
#     to: 'on'
#     from: 'off'
#   action:
#     - service: automation.turn_on
#       entity_id: automation.master_bedroom_auto_light_on
#     - service: timer.cancel
#       entity_id: timer.main_light_mb
#     - service: timer.start
#       entity_id: timer.main_light_mb

# # ##################################
# # Master Bedroom - Auto Light Off
# # ##################################
# - alias: master_bedroom_auto_light_off
#   initial_state: 'true'
#   trigger:
#   - platform: event
#     event_type: timer.finished
#     event_data:
#       entity_id: timer.main_light_mb
#   condition:
#     - condition: state
#       entity_id: binary_sensor.tod_day
#       state: 'on'
#   action:
#     - service: light.turn_off
#       entity_id: light.round_led_mb

# ##################################
# Master Bedroom - Auto Light On
# ##################################
# - alias: master_bedroom_auto_light_on
#   initial_state: 'true'
#   trigger:
#     - platform: event
#       event_type: xiaomi_aqara.motion
#       event_data:
#         entity_id: binary_sensor.motion_sensor_158d0001e53cda
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: light.round_led_mb
#         state: 'off'
#       - condition: state
#         entity_id: binary_sensor.tod_day
#         state: 'on'
#       - condition: state
#         entity_id: sun.sun
#         state: below_horizon
#   action:
#     - service: light.turn_on
#       entity_id: light.round_led_mb
      
# ##################################
# Master Bedroom - Auto Ambilight On
# ##################################
# - alias: master_bedroom_auto_ambilight_light
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: light.round_led_mb
#   action:
#     - service: script.turn_on
#       data_template:
#         entity_id: script.master_bedroom_ambilight_{{ states('light.round_led_mb') | lower }}
