# #####################################################################################
#
# HALL BIG
#
# #####################################################################################
# Hall Big - Domofon Incoming Call
# ##################################
- alias: hall_big_domofon_incoming_call
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.esp32_domofon_incomingcall
      to: 'on'
  action:
    - service: automation.turn_off
      entity_id: automation.hall_big_domofon_incoming_call
#    - service: camera.snapshot
#      data:
#        entity_id: camera.uvc_g3_flex_window
#        filename: "/config/www/cam_captures/window.jpg"
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        message: "Звонок в домофон!"
        data:
          push:
            badge: 0
            category: "domofon_call"
    - service: script.turn_on
      entity_id: script.domofon_script
    - delay: '00:00:30'
    - service: automation.turn_on
      entity_id: automation.hall_big_domofon_incoming_call
    - delay: '00:15:00'
    - service: script.turn_on
      entity_id: script.domofon_check

# ##################################
# Hall Big - Domofon Auto Open On Arrival
# ##################################
- alias: hall_big_domofon_auto_open_on_arrival
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: person.dima
      to: 'home'
    - platform: state
      entity_id: person.sandra
      to: 'home'
    - platform: state
      entity_id: person.vova
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.domofon_auto_open_once
        state: 'off'
      - condition: state
        entity_id: input_boolean.domofon_auto_open
        state: 'off'
      - condition: template
        value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
    - service: notify.telegram
      data_template:
        message: >
          {% if trigger.from_state.attributes.friendly_name == "Dima" %} {{"\U0001F9D4"}} Дима прибыл домой!
          {% elif trigger.from_state.attributes.friendly_name == "Sandra" %} {{"\U0001F467"}} Саша прибыла домой!
          {% elif trigger.from_state.attributes.friendly_name == "Vova" %} {{"\U0001F471"}} Вова прибыл домой!
          {%endif%}
    - service_template: >
        {% if trigger.from_state.attributes.friendly_name != "Babayka"%} notify.telegram_{{ trigger.from_state.attributes.friendly_name|lower }}
        {%else%} script.noop
        {%endif%}
      data_template:
        message: "\U0001F4DE Домофон: Автооткрытие включено на 15мин! {% if is_state('binary_sensor.bottom_lock','off') or is_state('binary_sensor.upper_lock','off') %}Закрыт{%if is_state('binary_sensor.bottom_lock','off') %} нижний{%endif%}{%if is_state('binary_sensor.upper_lock','off')%} и верхний{%endif%} замок{%endif%}"
          
    - service: script.turn_on
      entity_id: script.domofon_mute_toggle
    - service: script.turn_on
      entity_id: script.domofon_auto_open_once_toggle
    - delay: '00:15:00'
    - service: script.turn_on
      entity_id: script.domofon_check

# ##################################
# Hall Big - Domofon auto off on door open\close
# ##################################
- alias: hall_big_domofon_off_on_door open_close
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001e5d6be
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.domofon_auto_open_once
      state: 'on'
    - condition: state
      entity_id: input_boolean.domofon_mute
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.domofon_check

# ##################################
# Hall Big - Domofon open door from iphone
# ##################################
- alias: hall_big_domofon_open_iphone
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DOMOFON_OPEN_DOOR
  action:
    service: script.turn_on
    entity_id: script.domofon_open_door

# ##################################
# Hall big - Domofon Open Button
# ##################################
- alias: hall_big_domofon_button_open
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0002f8dd54
        click_type: single
  action:
#    - service: camera.snapshot
#      data:
#        entity_id: camera.uvc_g3_flex_entrance
#        filename: "/config/www/cam_captures/entrance_domofon.jpg"
    - service: switch.turn_on
      entity_id: switch.esp32_domofon_relay1, switch.esp32_domofon_relay2
    - delay: '00:00:01'
    - service: switch.turn_on
      entity_id: switch.esp32_domofon_relay3
    - delay: '00:00:01'
    - service: switch.turn_off
      entity_id: switch.esp32_domofon_relay1, switch.esp32_domofon_relay2, switch.esp32_domofon_relay3
    - service: notify.telegram
      data_template:
        message: "\U0001f518 Домофон открыт вручную!"
        data:
          photo:
            #- file: /config/www/cam_captures/entrance_domofon.jpg
            - url: http://192.168.1.14:8123{{state_attr('camera.uvc_g3_flex_entrance','entity_picture')}}
              caption: "\U0001f518 Домофон открыт вручную!"

# ##################################
# Hall big - Domofon Auto Open Once
# ##################################
- alias: hall_big_domofon_button_auto_open_once
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0002f8dd54
        click_type: double
  action:
    - service: script.turn_on
      entity_id: script.domofon_auto_open_once_toggle
      
# ##################################
# Hall big - Domofon Auto Open 
# ##################################
- alias: hall_big_domofon_button_auto_open
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0002f8dd54
        click_type: long_click_press
  action:
    - service: script.turn_on
      entity_id: script.domofon_auto_open_toggle