# #####################################################################################
#
# HALL BIG
#
# #####################################################################################
# Hall Big - Auto Night Light On
# ##################################
- alias: hall_big_auto_night_light_on
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.motion
    #   event_data:
    #     entity_id: binary_sensor.motion_sensor_158d0001e05856
    - platform: state
      entity_id: binary_sensor.0x00158d0001e05856_occupancy, binary_sensor.unifi_motion_entrance, binary_sensor.0x00158d0002b43ad4_occupancy
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'off'
      #- condition: state
      #  entity_id: light.led_strip_hb
      #  state: 'off'
      - condition: state
        entity_id: light.lt11_1_led
        state: 'off'
      - condition: state
        entity_id: switch.0x00158d000223921b_switch_left #switch.wall_switch_left_158d000223921b
        state: 'off'
      - condition: state
        entity_id: switch.0x00158d000253f04a_switch_right #switch.wall_switch_right_158d000253f04a
        state: 'off'
  action:
    #- service: light.turn_on
    #  entity_id: light.led_strip_hb
    #  data:
    #    brightness_pct: 1
    #    kelvin: 3000
    - service: light.turn_on
      entity_id: light.lt11_1_led
      data_template: 
        brightness_pct: 45
        rgb_color: [255, 180, 107]
        white_value: 25
    - delay: '00:00:30'
    #- service: light.turn_off
    #  entity_id: light.led_strip_hb
    - service: light.turn_off
      entity_id: light.lt11_1_led


# ##################################
# Hall Big - Auto Light On
# ##################################
- alias: hall_big_auto_light_on
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.motion
    #   event_data:
    #     entity_id: binary_sensor.motion_hb #.motion_sensor_158d0001e05856, binary_sensor.motion_sensor_158d0002b482e9
    # - platform: event
    #   event_type: xiaomi_aqara.motion
    #   event_data:
    #     entity_id: binary_sensor.motion_sensor_158d0002b482e9
    - platform: state
      entity_id: binary_sensor.0x00158d0001e05856_occupancy, binary_sensor.0x00158d0002b482e9_occupancy #, binary_sensor.unifi_motion_entrance, binary_sensor.unifi_motion_hall
      from: 'off'
      to: 'on'
    # - platform: state
    #   entity_id: binary_sensor.motion_sensor_158d0002b482e9
    #   from: 'off'
    #   to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'on'
      - condition: state
        entity_id: binary_sensor.dark_mode
        state: 'off'
      - condition: state
        entity_id: light.led_strip_hb
        state: 'off'
      - condition: state
        entity_id: switch.0x00158d000223921b_switch_left #switch.wall_switch_left_158d000223921b
        state: 'off'
      - condition: state
        entity_id: switch.0x00158d000253f04a_switch_right #switch.wall_switch_right_158d000253f04a
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.led_strip_hb
      data_template: 
        brightness_pct: >
          {% if states('binary_sensor.workday_sensor')=='off' and states('sensor.time').split(':').0|int < 10 %}
            1
          {% else %}
            100
          {%endif%}
        kelvin: >
          {% if states('binary_sensor.workday_sensor')=='off' and states('sensor.time').split(':').0|int < 10 %}
            3000
          {% else %}
            5000
          {%endif%}

# ##################################
# Hall Big - Auto Night Light Off 60s without movements
# ##################################
- alias: hall_big_night_auto_off_60s
  initial_state: 'true'
  trigger:
    # - platform: state
    #   entity_id: binary_sensor.motion_sensor_158d0001e05856
    #   to: 'off'
    #   for:
    #     seconds: 30
    - platform: state
      entity_id: binary_sensor.0x00158d0001e05856_occupancy
      to: 'off'
      for: '00:00:30'
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'off'
  action:
    #- service: light.turn_off
    #  entity_id: light.led_strip_hb
     - service: light.turn_off
       entity_id: light.lt11_1_led

# ##################################
# Hall Big - Yeelight strip off
# ##################################
- alias: hall_big_yeelight_off
  initial_state: 'true'
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: light.led_strip_hb
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.led_strip_hb

      
# ##################################
# Hall Big - Auto Light Off 1m without movements
# ##################################
- alias: hall_big_auto_off_60s
  initial_state: 'true'
  trigger:
    #- platform: state
    #  entity_id: binary_sensor.motion_sensor_158d0001e05856
    #  to: 'off'
    #  for:
    #    seconds: 1
    #- platform: state
    #  entity_id: binary_sensor.motion_sensor_158d0002b482e9
    #  to: 'off'
    #  for:
    #    seconds: 1
    - platform: state
      entity_id: binary_sensor.motion_hb #, binary_sensor.unifi_motion_entrance, binary_sensor.unifi_motion_hall
      to: 'off'
      from: 'on'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.led_strip_hb
      
# ##################################
# Hall Big - Auto Light On when door opened
# ##################################
- alias: hall_big_main_door_open
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0001e5d6be_contact #binary_sensor.door_window_sensor_158d0001e5d6be
      from: 'off'
      to: 'on'
#  condition:
#    - condition: state
#      entity_id: light.led_strip_hb
#      state: 'off'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.main_door_open
        value: "{{as_timestamp(strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M'))}}"
    - service: timer.cancel
      entity_id: timer.main_door_open_hb
    - service: timer.start
      entity_id: timer.main_door_open_hb
    - service: light.turn_on
      entity_id: light.led_strip_hb
      data_template:
        brightness_pct: >
          {%- if is_state('binary_sensor.tod_day','off') -%}
          2
          {%- else -%}
          100
          {% endif %}
        kelvin: >
          {%- if is_state('binary_sensor.tod_day','off') -%}
          3000
          {%- else -%}
          5000
          {% endif %}
    - service: counter.increment
      entity_id: counter.main_door_hb
    - service: notify.telegram
      data_template:
        message: "\U0001f6aa Внимание! Входная дверь открыта! ({{states('sensor.time')}} {{states('sensor.date')}}, {{ states('counter.main_door_hb') }})"
    - service: notify.telegram_cam
      data_template:
        message: "\U0001f6aa Внимание! Входная дверь открыта! ({{states('sensor.time')}} {{states('sensor.date')}}, {{ states('counter.main_door_hb') }})"
    - delay: '00:00:09'
    - service: script.turn_on
      entity_id: script.open_door_photo

# # ##################################
# # Hall Big - Auto Light On Entrance
# # ##################################
# - alias: hall_big_auto_light_on_entrance
#   initial_state: 'false'
#   trigger:
#     # - platform: event
#     #   event_type: xiaomi_aqara.motion
#     #   event_data:
#     #     entity_id: binary_sensor.motion_sensor_158d0001e05856
#     - platform: state
#       entity_id: binary_sensor.0x00158d0001e05856_occupancy
#       from: 'off'
#       to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: numeric_state
#         entity_id: sensor.0x00158d0001e05856_illuminance #sensor.illuminnation_158d0001e05856
#         below: 10
#       - condition: state
#         entity_id: binary_sensor.tod_day
#         state: 'on'
#   action:
#     - service: switch.turn_on
#       entity_id: switch.0x00158d000223921b_switch_left #switch.wall_switch_left_158d000223921b

# # ##################################
# # Hall Big - Auto Light On Fridge
# # ##################################
# - alias: hall_big_auto_light_on_fridge
#   initial_state: 'false'
#   trigger:
#     # - platform: event
#     #   event_type: xiaomi_aqara.motion
#     #   event_data:
#     #     entity_id: binary_sensor.motion_sensor_158d0002b482e9
#     - platform: state
#       entity_id: binary_sensor.0x00158d0002b482e9_occupancy
#       from: 'off'
#       to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: numeric_state
#         entity_id: sensor.0x00158d0002b482e9_illuminance #sensor.illuminnation_158d0002b482e9
#         below: 10
#       - condition: state
#         entity_id: binary_sensor.tod_day
#         state: 'on'
#   action:
#     - service: switch.turn_on
#       entity_id: switch.0x00158d000253f04a_switch_right #switch.wall_switch_right_158d000253f04a
      
# ##################################
# Hall big - Timer start on light on
# ################################## 
- alias: hall_big_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x00158d000223921b_switch_left #switch.wall_switch_left_158d000223921b
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: switch.0x00158d000253f04a_switch_right #switch.wall_switch_right_158d000253f04a
      to: 'on'
      from: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_hb
    - service: timer.start
      entity_id: timer.main_light_hb
    
# ##################################
# Hall big - Timer off
# ################################## 
- alias: hall_big_timer_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x00158d000223921b_switch_left #switch.wall_switch_left_158d000223921b
      to: 'off'
      from: 'on'
    - platform: state
      entity_id: switch.0x00158d000253f04a_switch_right #switch.wall_switch_right_158d000253f04a
      to: 'off'
      from: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_hb

# ##################################
# Hall big - Auto Light Off 10m without movements
# ##################################
- alias: hall_big_auto_off_10m
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.main_light_hb
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d000223921b_switch_left, switch.0x00158d000253f04a_switch_right

# ##################################
# Hall big - Timer restart with movement
# ################################## 
- alias: hall_big_timer_restart
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.motion
    #   event_data:
    #     entity_id: binary_sensor.motion_sensor_158d0001e05856
    - platform: state
      entity_id: binary_sensor.0x00158d0001e05856_occupancy, binary_sensor.0x00158d0002b482e9_occupancy
      from: 'off'
      to: 'on'
    # - platform: event
    #   event_type: xiaomi_aqara.motion
    #   event_data:
    #     entity_id: binary_sensor.motion_sensor_158d0002b482e9
    # - platform: state
    #   entity_id: binary_sensor.0x00158d0002b482e9_occupancy
    #   from: 'off'
    #   to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.0x00158d000223921b_switch_left #switch.wall_switch_left_158d000223921b
        state: 'on'
      - condition: state
        entity_id: switch.0x00158d000253f04a_switch_right #switch.wall_switch_right_158d000253f04a
        state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_hb
    - service: timer.start
      entity_id: timer.main_light_hb

# ##################################
# Hall Big - Entrance light On from Fridge
# ##################################
- alias: hall_big_entrance_light_on_from_fridge
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x00158d000253f04a_switch_left #switch.wall_switch_left_158d000253f04a
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.0x00158d000253f04a_switch_left #switch.wall_switch_left_158d000253f04a
      from: 'on'
      to: 'off'
  action:
    - service: switch.toggle
      entity_id: switch.0x00158d000223921b_switch_left #switch.wall_switch_left_158d000223921b

# ##################################
# Hall Big - Fridge light On from Entrance
# ##################################
- alias: hall_big_fridge_light_on_from_entrance
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x00158d000223921b_switch_right #switch.wall_switch_left_158d000253f04a
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.0x00158d000223921b_switch_right #switch.wall_switch_left_158d000253f04a
      from: 'on'
      to: 'off'
  action:
    - service: switch.toggle
      entity_id: switch.0x00158d000253f04a_switch_right #switch.wall_switch_right_158d000253f04a


# ##################################
# Hall Big - LED Strip Reset 
# ##################################
- alias: hall_big_led_strip_reset
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.led_strip_hb
      to: 'unavailable'
      for:
        minutes: 5
  action:
    - service: script.turn_on
      entity_id: script.led_strip_restart

# ##################################
# Hall Big - LED Strip Power Switch Turn On
# ##################################
- alias: hall_big_led_strip_switch_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x00158d00023e5812_switch #switch.wall_plug_158d00023e5812
      to: 'off'
      for:
        seconds: 45
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d00023e5812_switch #switch.wall_plug_158d00023e5812
      
# ##################################
# Hall Big - Wadrobe Auto Light On
# ##################################
- alias: hall_big_wadrobe_auto_light_on
  initial_state: 'false'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0002b43ad4_occupancy
      from: 'off'
      to: 'on'
  action:
    - service: script.turn_on
      data_template: 
        entity_id: >
          {% if is_state('binary_sensor.tod_night','on') or (states('sensor.time').split(':').0|int < 10 and states('binary_sensor.workday_sensor')=='off') %}
            script.wadrobe_mirror_led_night_mode
          {% else %}
            script.wadrobe_mirror_led_day_mode
          {%endif%}

# ##################################
# Hall Big - Wadrobe LED Timer start on light on
# ################################## 
- alias: hall_big_wadrobe_led_timer_start
  initial_state: 'false'
  trigger:
    - platform: state
      entity_id: light.lt11_1_led
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.wadrobe_led_strip_hb
    - service: timer.start
      entity_id: timer.wadrobe_led_strip_hb

# ##################################
# Hall Big - Wadrobe LED Timer restart
# ################################## 
- alias: hall_big_wadrobe_led_timer_restart
  initial_state: 'false'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0002b43ad4_occupancy, binary_sensor.unifi_motion_entrance
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.lt11_1_led
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.wadrobe_led_strip_hb
    - service: timer.start
      entity_id: timer.wadrobe_led_strip_hb

# ##################################
# Hall Big - Wadrobe LED Timer stop
# ################################## 
- alias: hall_big_wadrobe_led_timer_off
  initial_state: 'false'
  trigger:
    - platform: state
      entity_id: light.lt11_1_led
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.wadrobe_led_strip_hb
      
# ##################################
# Hall Big - Wadrobe LED Auto Light Off
# ################################## 
- alias: hall_big_wadrobe_led_auto_off
  initial_state: 'false'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.wadrobe_led_strip_hb
  action:
    - service: light.turn_off
      entity_id: light.lt11_1_led