# #####################################################################################
#
# HALL BIG
#
# #####################################################################################
# Hall Big - Motion Outside
# ##################################
- alias: hall_big_motion_outside_esp32
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.esp32_domofon_motion
      from: 'off'
      to: 'on'
  action:
    - delay: '00:00:02'
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "ESP32 - Движение за дверью! {{states('sensor.time')}} {{states('sensor.date')}} "
        data:
          photo:
          - url: http://192.168.1.14:8123{{state_attr('camera.door_hb','entity_picture')}}
            caption: "ESP32 - Движение за дверью! {{states('sensor.time')}} {{states('sensor.date')}} "

# ##################################
# Hall Big - Motion Outside
# ##################################
- alias: hall_big_motion_outside_motioneye
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.pinhole_camera_motion
      from: 'off'
      to: 'on'
  action:
    - delay: '00:00:05'
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "Движение за дверью! {{states('sensor.time')}} {{states('sensor.date')}} "
        data:
          photo:
          - url: http://192.168.1.14:8123{{state_attr('camera.door_hb','entity_picture')}}
            caption: "MotionEye - Движение за дверью! {{states('sensor.time')}} {{states('sensor.date')}} "