# #####################################################################################
#
# BATHROOM
#
# #####################################################################################
# Bathroom Fan - On 10m Manual
# ##################################
- alias: bathroom_fan_on_manual
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b94abe
        click_type: single
  condition:
    - condition: state
      entity_id: switch.plug_158d0001f9ebd8
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.plug_158d0001f9ebd8
    - delay: '00:10:00'
    - service: switch.turn_off
      entity_id: switch.plug_158d0001f9ebd8

# ##################################
# Bathroom Fan - Off Manual
# ##################################
- alias: bathroom_fan_off_manual
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b94abe
        click_type: single
  condition:
    - condition: state
      entity_id: switch.plug_158d0001f9ebd8
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.plug_158d0001f9ebd8

# ##################################
# Bathroom Fan - Fans - Off
# ##################################
- alias: bathroom_fans_check_off
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: numeric_state
      entity_id: sensor.humidity_b_delta
      below: 10
    - condition: state
      entity_id: switch.plug_158d0001f9ebd8
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.plug_158d0001f9ebd8
    - delay: '00:15:00'
    - service: switch.turn_off
      entity_id: switch.plug_158d0003926263
    - service: automation.turn_on
      entity_id: automation.bathroom_bottom_fan_toggle


# ##################################
# Bathroom Fan - Fans - On
# ##################################
- alias: bathroom_fans_ckeck_on
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: numeric_state
      entity_id: sensor.humidity_b_delta
      above: 10
    - condition: state
      entity_id: switch.plug_158d0001f9ebd8
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.plug_158d0001f9ebd8, switch.plug_158d0003926263
    - service: automation.turn_off
      entity_id: automation.bathroom_bottom_fan_toggle

# ##################################
# Bathroom - Timer restart with movement
# ################################## 
- alias: bathroom_timer_restart
  initial_state: 'true'
  trigger:
  - platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id:  binary_sensor.motion_sensor_158d000236bc6d
  condition:
    - condition: state
      entity_id: switch.wall_switch_right_158d0002a36e26
      state: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.timer_b
  - service: timer.start
    entity_id: timer.timer_b

# ##################################
# Bathroom - Timer off
# ################################## 
- alias: bathroom_timer_off
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: switch.wall_switch_right_158d0002a36e26
    to: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.timer_b
    
# ##################################
# Bathroom - Timer start on light on
# ################################## 
- alias: bathroom_timer_on
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.wall_switch_right_158d0002a36e26
    to: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.timer_b
  - service: timer.start
    entity_id: timer.timer_b

# ##################################
# Bathroom - Timer pause on
# ################################## 
- alias: bathroom_timer_pause_on
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d000236bc6d
  condition:
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d0002a14c5e
      state: 'off'
    - condition: state
      entity_id: switch.wall_switch_right_158d0002a36e26
      state: 'on'
  action:
  - service: timer.pause
    entity_id: timer.timer_b
  - service: automation.turn_off
    entity_id: automation.bathroom_timer_restart


# ##################################
# Bathroom - Timer pause off
# ################################## 
- alias: bathroom_timer_pause_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002a14c5e
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.wall_switch_right_158d0002a36e26
      state: 'on'
  action:
  - service: timer.start
    entity_id: timer.timer_b
  - service: automation.turn_on
    entity_id: automation.bathroom_timer_restart
  

# ##################################
# Bathroom - Auto Light On
# ##################################
- alias: bathroom_auto_light_on
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d000236bc6d
  action:
  - service: switch.turn_on
    entity_id: switch.wall_switch_right_158d0002a36e26
  
# ##################################
# Bathroom - Auto Light Off
# ##################################
- alias: bathroom_auto_light_off
  initial_state: 'true'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_b
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d0002a36e26

# ##################################
# Bathroom - Auto Light Disable if Door is Closed and there is movement detected
# ##################################
- alias: bathroom_auto_light_disable
  initial_state: 'false'
  trigger:
    platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d000236bc6d
  condition:
    condition: state
    entity_id: binary_sensor.door_window_sensor_158d0002a14c5e
    state: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.timer_b

# ##################################
# Bathroom - Water Leak Detected
# ##################################
- alias: bathroom_water_leak_detected
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor_158d0002373a67
    from: 'off'
    to: 'on'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.mpd
          - media_player.home_mini_k
        volume_level: '0.3'
    - service: tts.yandextts_say
      entity_id: 
        - media_player.mpd
        - media_player.home_mini_k
      data_template:
        message: 'Вним+ание! Вним+ание! Обнар+ужена ут+ечка вод+ы в в+анне! Обнар+ужена ут+ечка вод+ы в в+анне! Вод+а перекрыв+ается!'
    - service: notify.telegram
      data_template:
        message: "\U000026d4 Внимание! Обнаружена утечка воды в ванне! Обнаружена утечка воды в ванне! Вода перекрывается!"
    - service: switch.turn_on
      entity_id: switch.plug_158d00020d8679
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.plug_158d00020d8679
    - service: tts.yandextts_say
      entity_id: 
        - media_player.mpd
        - media_player.home_mini_k
      data_template:
        message: 'Вним+ание! Вод+а перекр+ыта! Устран+ите прот+ечку вод+ы в в+анне дл+я включ+ения вод+ы!'
    - service: notify.telegram
      data_template:
        message: "\U000026d4 Внимание! Вода перекрыта! Устраните протечку воды в ванне для включения воды!"
    - service: notify.telegram
      data:
        title: "Внимание!"
        message: "Сработал датчик протечки в ванне! Краны закрыты!"

# ##################################
# Bathroom - Water Leak - Off
# ##################################
- alias: bathroom_water_leak_off
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor_158d0002373a67
    from: 'on'
    to: 'off'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.mpd
          - media_player.home_mini_k
        volume_level: '0.3'
    - service: tts.yandextts_say
      entity_id: 
        - media_player.mpd
        - media_player.home_mini_k
      data_template:
        message: 'Прот+ечка вод+ы в в+анне устранен+а! Спас+ибо!'
    - service: notify.telegram
      data_template:
        message: "\U00002705 Протечка воды в ванне устранена!"

# ##################################
# Bathroom Water Valves Test
# ##################################
- alias: bathroom_water_valves_test
  initial_state: 'true'
  trigger:
    platform: time
    at: '00:01:00'
  condition:
    condition: time
    weekday:
      - mon
      #- wed
      - fri
  action:
    - service: notify.telegram
      data_template: 
        message: "\U0001f6b0 Проверка кранов - закрываем!"
    - service: switch.turn_on
      entity_id: switch.plug_158d00020d8679
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.plug_158d00020d8679
    - delay: '00:00:05'
    - service: notify.telegram
      data_template: 
        message: "\U0001f6b0 Проверка кранов - открываем!"
    - service: switch.turn_on
      entity_id: switch.plug_158d0001f54f90
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.plug_158d0001f54f90
    - service: notify.telegram
      data_template: 
        message: "\U00002705 Проверка кранов завершена!"

# ##################################
# Bathroom - Washing Machine notification
# ##################################
- alias: bathroom_washing_machine
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.washer_b
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.washer_b
      from: 'on'
      to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_uptime
      above: 0.083
      #value_template: {{ states.sensor.ha_uptime|float * 60 }}
  action:
    - service: notify.telegram
      data_template: 
        message: "{% if is_state('binary_sensor.washer_b','on') %}\U000023F3 Стирка начата!{% else %}\U0000231B Стирка завершена! Время стирки составило {{ ( (as_timestamp(strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M'))| round(0) - as_timestamp(states.timer.timer_washer_b.last_changed)| int) / 60 )| round(0) }}мин.{% endif %}"
    - service_template: >
        {% if is_state('binary_sensor.tod_day','on') %}
          script.washing_machine_tts
        {%else%}
          script.noop
        {% endif %}
    - service: script.turn_on
      data_template: 
        entity_id: "{% if is_state('binary_sensor.washer_b','on') %}script.washer_timer_on{% else %}script.washer_timer_off{% endif %}"
          
# ##################################
# Bathroom - Bottom Fan On
# ##################################
- alias: bathroom_bottom_fan
  initial_state: 'true'
  trigger:
    - platform: time
      at: '07:00:03'
    - platform: time
      at: '23:00:03'
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'off'
  action:
  - service_template: "switch.turn_switch.turn_{%if states('binary_sensor.tod_day')%}off{%else%}on{%endif%}"
    data:
      entity_id: switch.plug_158d0003926263

# ##################################
# Bathroom - Bottom Fan
# ##################################
- alias: bathroom_bottom_fan_manual
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b94abe
        click_type: double
  action:
    - service: switch.toggle
      entity_id: switch.plug_158d0003926263
      
# ##################################
# Bathroom - Bottom Fan Toggle
# ##################################
- alias: bathroom_bottom_fan_toggle
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/30"
  condition:
    condition: and
    conditions: 
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'off'
      - condition: state
        entity_id: input_boolean.security_mode
        state: 'off'
  action:
    - service: switch.toggle
      entity_id: switch.plug_158d0003926263

# ##################################
# Bathroom - Light Toggle with Repeater
# ##################################
- alias: bathroom_light_toggle_repeater
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d0001e0a622
  action:
    - service: switch.toggle
      entity_id: switch.wall_switch_right_158d0002a36e26
