# ##################################
# Emergency - RPI connection lost
# ##################################
- alias: emergency_rpi_lost
  initial_state: 'on'
  trigger:
   platform: state
   entity_id: sensor.rpi_state
   to: 'unavailable'
   for: "00:00:10"
#  condition:
#    - condition: state
#      entity_id: automation.06_bathroom_cell_power
#      state: 'off'     
  action:
    - service: notify.telegram
      data:
        message: "\U0000274C Потеря связи с RPI!"
        
# ##################################
# Emergency - j3455 connection lost
# ##################################
- alias: emergency_j3455_lost
  initial_state: 'on'
  trigger:
   platform: state
   entity_id: sensor.j3455_state
   to: 'unavailable'
   for: "00:00:10"
#  condition:
#    - condition: state
#      entity_id: automation.06_bathroom_cell_power
#      state: 'off'     
  action:
    - service: notify.telegram
      data:
        message: "\U0000274C Потеря связи с j3455!"
#    - service: homeassistant.turn_on
#      entity_id: group.scenario

# ##################################
# Emergency - RPI connection restored
# ##################################
- alias: emergency_rpi_restored
  initial_state: 'on'
  trigger:
   platform: state
   entity_id: sensor.rpi_state
   from: 'unavailable'
  action:
    - service: notify.telegram
      data:
        message: "\U00002714 Связь с RPI восстановлена!"
        
# ##################################
# Emergency - RPI connection restored
# ##################################
- alias: emergency_j3455_restored
  initial_state: 'on'
  trigger:
   platform: state
   entity_id: sensor.j3455_state
   from: 'unavailable'
  action:
    - service: notify.telegram
      data:
        message: "\U00002714 Связь с j3455 восстановлена!"