# #####################################################################################
#
# KITCHEN
#
# #####################################################################################
# Kitchen Table Lamp (Yeelight E27 Color) On
# ##################################
- alias: kitchen_table_lamp_on_if_lamp_off
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001ef61be
      click_type: single
  condition:
    condition: state
    entity_id: light.led_color_k
    state: 'off'    
  action:
  - service: light.turn_on
    entity_id: light.led_color_k
    data_template:
      brightness_pct: 100
      kelvin: 5000
      
# ##################################
# Kitchen Table Lamp (Yeelight E27 Color) Off
# ##################################
- alias: kitchen_table_lamp_off_if_lamp_on
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001ef61be
      click_type: single
  condition:
    condition: state
    entity_id: light.led_color_k
    state: 'on'    
  action:
  - service: light.turn_off
    entity_id: light.led_color_k

# ##################################
# Kitchen Table Lamp (Yeelight E27 Color) to bright
# ##################################
- alias: kitchen_table_lamp_to_bright
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001ef61be
      click_type: double
  action:
  - service: light.turn_on
    entity_id: light.led_color_k
    data_template:
      brightness_pct: 100
      kelvin: 5000

# ##################################
# Kitchen Table Lamp (Yeelight E27 Color) to midnight
# ##################################
- alias: kitchen_table_lamp_to_midnight
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001ef61be
      click_type: long_click_press
  action:
  - service: light.turn_on
    entity_id: light.led_color_k
    data_template:
      brightness_pct: 5
      kelvin: 3000
      
# ##################################
# Kitchen - Timer restart with movement
# ################################## 
- alias: kitchen_timer_restart
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0002b4729d
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0002b48381
  condition:
    - condition: state
      entity_id: switch.wall_switch_right_158d0002a36f7f
      state: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.main_light_k
  - service: timer.start
    entity_id: timer.main_light_k

# ##################################
# Kitchen - Timer off
# ################################## 
- alias: kitchen_timer_off
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: switch.wall_switch_right_158d0002a36f7f
    to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_k
    - service: automation.turn_off
      entity_id: automation.kitchen_auto_light_on
    - delay: '00:00:10'
    - service: automation.turn_on
      entity_id: automation.kitchen_auto_light_on
    
    
# ##################################
# Kitchen - Timer start on light on
# ################################## 
- alias: kitchen_timer_on
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.wall_switch_right_158d0002a36f7f
    to: 'on'
  # condition:
  #   condition: time
  #   after: '07:00:00'
  #   before: '21:00:00'
  action:
    - service: automation.turn_on
      entity_id: automation.kitchen_auto_light_on
    - service: timer.cancel
      entity_id: timer.main_light_k
    - service: timer.start
      entity_id: timer.main_light_k
    - service: switch.turn_off
      entity_id: switch.plug_158d000216528c
    - service: automation.turn_off
      entity_id: automation.kitchen_auto_night_light
        
# ##################################
# Kitchen - Auto Light Off
# ##################################
- alias: kitchen_auto_light_off
  initial_state: 'true'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.main_light_k
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d0002a36f7f

# ##################################
# Kitchen - Auto Light On
# ##################################
- alias: kitchen_auto_light_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0002b4729d
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0002b48381
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.wall_switch_right_158d0002a36f7f
        state: 'off'
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_right_158d0002a36f7f


# ##################################
# Kitchen - Auto Night Light
# ##################################
- alias: kitchen_auto_night_light
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0002b4729d
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0002b48381
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.plug_158d000216528c
        state: 'off'
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'off'
      - condition: state
        entity_id: switch.wall_switch_right_158d0002a36f7f
        state: 'off'
      - condition: state
        entity_id: switch.wall_switch_left_158d0002a365df
        state: 'off'
      - condition: state
        entity_id: switch.wall_switch_right_158d0002a365df
        state: 'off'
      - condition: state
        entity_id: switch.esp32_kitchen_light
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.plug_158d000216528c
    - delay: '00:00:30'
    - service: switch.turn_off
      entity_id: switch.plug_158d000216528c
    - service: automation.turn_off
      entity_id: automation.kitchen_auto_night_light
     
# ##################################
# Kitchen - Water Leak Detected
# ##################################
- alias: kitchen_water_leak_detected
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor_158d00023297e7
    from: 'off'
    to: 'on'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.mpd
          - media_player.home_mini_k
        volume_level: '0.3'
    - service: tts.yandextts_say
      entity_id: 
        - media_player.mpd
        - media_player.home_mini_k
      data_template:
        message: 'Вним+ание! Вним+ание! Обнар+ужена ут+ечка вод+ы н+а к+ухне! Обнар+ужена ут+ечка вод+ы н+а к+ухне! Вод+а перекрыв+ается!'
    - service: notify.telegram
      data_template:
        message: "\U000026d4 Внимание! Обнаружена утечка воды на кухне! Обнаружена утечка воды на кухне! Вода перекрывается!"
    - service: switch.turn_on
      entity_id: switch.plug_158d00020d8679
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.plug_158d00020d8679
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.mpd
          - media_player.home_mini_k
        volume_level: '0.3'
    - service: tts.yandextts_say
      entity_id: 
        - media_player.mpd
        - media_player.home_mini_k
      data_template:
        message: 'Вним+ание! Вод+а перекр+ыта! Устран+ите прот+ечку вод+ы н+а к+ухне дл+я включ+ения вод+ы!'
    - service: notify.telegram
      data_template:
        message: "\U000026d4 Внимание! Вода перекрыта! Устраните протечку воды на кухне для включения воды!"
    - service: notify.notify
      data:
        title: "Внимание!"
        message: "Сработал датчик протечки на кухне! Краны закрыты!"

# ##################################
# Kitchen - Water Leak Off
# ##################################
- alias: kitchen_water_leak_off
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor_158d00023297e7
    from: 'on'
    to: 'off'
  condition:
  
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.mpd
          - media_player.home_mini_k
        volume_level: '0.3'
    - service: tts.yandextts_say
      entity_id: 
        - media_player.mpd
        - media_player.home_mini_k
      data_template:
        message: 'Прот+ечка вод+ы н+а к+ухне устранен+а! Спас+ибо!'
    - service: notify.telegram
      data_template:
        message: "\U00002705 Протечка воды в кухне устранена!"

# ##################################
# Kitchen - Sockets on
# ##################################
- alias: kitchen_sockets_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0002b4729d
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0002b48381
  condition:
      - condition: state
        entity_id: switch.plug_158d000232481a
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.plug_158d000232481a, switch.plug_158d00028c9875, switch.plug_158d00028a54e4, switch.plug_158d0001e85086
#    - service: homeassistant.turn_on
#      entity_id: automation.kitchen_check_tv_box

# ##################################
# Kitchen - TV box Check
# ##################################
- alias: kitchen_check_tv_box
  initial_state: 'false'
  trigger:
    platform: state
    entity_id: binary_sensor.tv_box
    to: 'on'
  condition:
      - condition: state
        entity_id: binary_sensor.tv_k
        state: 'off'
  action:
    - delay: '00:01:00'
    - service: script.turn_on
      entity_id: script.tv_box_k_toggle
    - service: homeassistant.turn_off
      entity_id: automation.kitchen_check_tv_box

# ##################################
# Kitchen - TV Box Off with TV Off
# ##################################
- alias: kitchen_tv_box_off_tv_off
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
      - condition: state
        entity_id: binary_sensor.tv_box
        state: 'on'
      - condition: state
        entity_id: binary_sensor.tv_k
        state: 'off'
        for:
          minutes: 1
  action:
    - service: script.turn_on
      entity_id: script.tv_box_k_toggle

# ##################################
# Kitchen - Weather announcement
# ##################################
- alias: kitchen_weather_announcement
  initial_state: 'false'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0002b4729d
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0002b48381
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:20:00'
        before: '07:30:00'
      - condition: template
        value_template: "{{(as_timestamp(strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M'))-as_timestamp(state_attr('automation.kitchen_weather_announcement', 'last_triggered')))|int(0) > 601 }}"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.weather_announcement_flag
    - service: script.weather_tts
      data_template:
        entity_id: media_player.home_mini_k
        volume_level: '0.3'
    #- service: script.weather_telegram

# ##################################
# Kitchen - Smoke Detected
# ##################################
- alias: kitchen_smoke_detected
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.smoke_sensor_158d0002c92f31
      to: 'on'
  action: 
    - service: notify.telegram
      data_template:
        message: ' Внимание! Сработал датчик дыма!'
        
# ##################################
# Kitchen - Gas Detected
# ##################################
- alias: kitchen_gas_detected
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.natgas_sensor_158d00024bcf85
      to: 'on'
  action: 
    - service: notify.telegram
      data_template:
        message: ' Внимание! Сработал датчик газа!'

# ##################################
# Kitchen - Work Light L
# ##################################
- alias: kitchen_work_light_l
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00023e5f2a
      click_type: single
  action:
  - service: switch.toggle
    entity_id: switch.wall_switch_left_158d0002a365df

# ##################################
# Kitchen - Work Light R
# ##################################
- alias: kitchen_work_light_R
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001ef609b
      click_type: single
  action:
  - service: switch.toggle
    entity_id: switch.wall_switch_right_158d0002a365df
    
# ##################################
# Kitchen - Work Light Off
# ##################################
- alias: kitchen_work_light_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001ef609b
        click_type: double
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00023e5f2a
        click_type: double
  action:
  - service_template: switch.turn_{%if is_state('switch.wall_switch_right_158d0002a365df','on') or is_state('switch.wall_switch_left_158d0002a365df','on')%}off{%else%}on{%endif%}
    entity_id: switch.wall_switch_right_158d0002a365df, switch.wall_switch_left_158d0002a365df

# ##################################
# Kitchen - Hood On - Vent Close
# ##################################
- alias: kitchen_ventilation_auto
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.hood_k
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_uptime
      above: 5
  action: 
    - service_template: >
        script.kitchen_vent_{%if is_state('binary_sensor.hood_k','on')%}close{%elif is_state('binary_sensor.hood_k','off')%}open{%endif%}

# ##################################
# Kitchen - Hood Fan
# ##################################
- alias: kitchen_hood_fan
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d0001e0784e
      #click_type: single
  action:
  - service: switch.toggle
    entity_id: switch.esp32_kitchen_fan1

# ##################################
# Kitchen - Hood Light
# ##################################
- alias: kitchen_hood_light
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0001e0784e
      #click_type: single
  action:
  - service: switch.toggle
    entity_id: switch.esp32_kitchen_light