# ##################################
# Bathroom - Dima Location changing
# ################################## 
- alias: location_dima
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: person.dima
  action:
    service: notify.telegram_errors
    data_template:
      message: 'Dima: {{ now().strftime("%d.%m.%Y-%H%M%S") }} from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'
        
# ##################################
# Bathroom - Sandra Location changing
# ################################## 
- alias: location_sandra
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: person.sandra
  action:
    service: notify.telegram_errors
    data_template:
      message: 'Sandra: {{ now().strftime("%d.%m.%Y-%H%M%S") }} from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'
        
# ##################################
# Bathroom - Vova Location changing
# ################################## 
- alias: location_vova
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: person.vova
  action:
    service: notify.telegram_errors
    data_template:
      message: 'Vova: {{ now().strftime("%d.%m.%Y-%H%M%S") }} from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'
        
# ##################################
# Bathroom - Sasha Location changing
# ################################## 
- alias: location_sasha
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: person.sasha
  action:
    service: notify.telegram_errors
    data_template:
      message: 'Sasha: {{ now().strftime("%d.%m.%Y-%H%M%S") }} from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'