# #####################################################################################
#
# MASTERBEDROOM
#
# #####################################################################################
# MB Table Lamp (Philips E27) On
# ##################################
- alias: master_bedroom_table_lamp_on_if_lamp_off
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00023d3116
        click_type: single
    #- platform: event
    #  event_type: xiaomi_aqara.movement
    #  event_data:
    #     entity_id: binary_sensor.vibration_158d0002a2412d
    #     movement_type: vibrate 
    #- platform: event
    #  event_type: xiaomi_aqara.movement
    #  event_data:
    #     entity_id: binary_sensor.vibration_158d0002a2412d
    #     movement_type: tilt
  condition:
    condition: state
    entity_id: light.philips_e27_mb
    state: 'off'    
  action:
  - service: light.turn_on
    entity_id: light.philips_e27_mb

# ##################################
# Master_bedroom Table Lamp (Philips E27) Off
# ##################################
- alias: master_bedroom_table_lamp_off_if_lamp_on
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      #entity_id: binary_sensor.switch_158d00016bdb4a
      entity_id: binary_sensor.switch_158d00023d3116
      click_type: single
  condition:
    condition: state
    entity_id: light.philips_e27_mb
    state: 'on'    
  action:
  - service: light.turn_off
    entity_id: light.philips_e27_mb

# ##################################
# Master_bedroom Table Lamp (Philips E27) - Switch to Bright
# ##################################
- alias: master_bedroom_table_lamp_bright
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      #entity_id: binary_sensor.switch_158d00016bdb4a
      entity_id: binary_sensor.switch_158d00023d3116
      click_type: double
  action:
    service: xiaomi_miio.light_set_scene
    entity_id: light.philips_e27_mb
    data:
       scene: 1

# ##################################
# Master_bedroom Table Lamp (Philips E27) - Switch to Mid-Night
# ##################################
- alias: master_bedroom_table_lamp_night
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      #entity_id: binary_sensor.switch_158d00016bdb4a
      entity_id: binary_sensor.switch_158d00023d3116
      click_type: long_click_press
  action:
    service: xiaomi_miio.light_set_scene
    entity_id: light.philips_e27_mb
    data:
        scene: 4

# ##################################        
# Master Bedroom Main Lamp (Xiaomi Round LED) - On
# ##################################
- alias: master_bedroom_main_lamp_on_if_lamp_off
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d00013e6aa5
      click_type: single
  condition:
    condition: state
    entity_id: light.round_led_mb
    state: 'off'    
  action:
  - service: light.turn_on
    entity_id: light.round_led_mb
    data_template:
      brightness_pct: 95
      kelvin: 5000
      
# ##################################
# Master Bedroom Main Lamp (Xiaomi Round LED) - Off
# ##################################
- alias: master_bedroom_main_lamp_off_if_lamp_on
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d00013e6aa5
      click_type: single
  condition:
    condition: state
    entity_id: light.round_led_mb
    state: 'on'    
  action:
  - service: light.turn_off
    entity_id: light.round_led_mb

# ##################################
# Master Bedroom Main Lamp (Xiaomi Round LED) - Brightness change with left button 33%
# ##################################
- alias: master_bedroom_main_lamp_on_30_if_lamp_off
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d00013e6aa5
      click_type: single
  condition:
    condition: state
    entity_id: light.round_led_mb
    state: 'off'    
  action:
  - service: light.turn_on
    entity_id: light.round_led_mb
    data_template:
      brightness_pct: 5
      kelvin: 3000
      
# ##################################
# Master Bedroom Main Lamp (Xiaomi Round LED) - Turn Off with Left Button
# ##################################
- alias: master_bedroom_main_lamp_off_if_lamp_on_with_left_button
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d00013e6aa5
      click_type: single
  condition:
    condition: state
    entity_id: light.round_led_mb
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.round_led_mb
    
# ##################################
# Master Bedroom - Round LED Reset 
# ##################################
- alias: master_bedroom_round_led_reset
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.round_led_mb
    to: 'unavailable'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day_long
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.round_led_restart
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Round LED MB restart done!"

# ##################################
# Master Bedroom - Round LED status check
# ##################################
- alias: master_bedroom_round_led_status_check
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:00:01'
  condition:
    condition: state
    entity_id: light.round_led_mb
    state: 'unavailable'
  action:
    - service: script.turn_on
      entity_id: script.round_led_restart
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Round LED MB restart done(morning)!"
      
# ##################################
# Master Bedroom - Round LED Power Switch Turn On
# ##################################
- alias: master_bedroom_round_led_switch_on
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: switch.plug_158d0002482619
    to: 'off'
    for:
      seconds: 3
  action:
    - service: switch.turn_on
      entity_id: switch.plug_158d0002482619