# #####################################################################################
#
# MASTERBEDROOM
#
# #####################################################################################
# MB Table Lamp (Philips E27) Toggle
# ##################################
- alias: master_bedroom_table_lamp_toggle
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00023d3116
        click_type: single
    #- platform: event
    #  event_type: xiaomi_aqara.movement
    #  event_data:
    #     entity_id: binary_sensor.vibration_158d0002a2412d
    #     movement_type: vibrate 
    #- platform: event
    #  event_type: xiaomi_aqara.movement
    #  event_data:
    #     entity_id: binary_sensor.vibration_158d0002a2412d
    #     movement_type: tilt
  action:
    - service: light.toggle
      entity_id: light.philips_e27_mb

# ##################################
# Master_bedroom Table Lamp (Philips E27) - Switch to Bright
# ##################################
- alias: master_bedroom_table_lamp_bright
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00023d3116
        click_type: double
  action:
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_mb
      data:
        scene: 1

# ##################################
# Master_bedroom Table Lamp (Philips E27) - Switch to Mid-Night
# ##################################
- alias: master_bedroom_table_lamp_night
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00023d3116
        click_type: long_click_press
  action:
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_mb
      data:
        scene: 4

# ##################################        
# Master Bedroom Main Lamp (Xiaomi Round LED) - On
# ##################################
- alias: master_bedroom_main_lamp_on_if_lamp_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d00013e6aa5
        click_type: single
  condition:
    - condition: state
      entity_id: light.round_led_mb
      state: 'off'    
  action:
    - service: light.turn_on
      entity_id: light.round_led_mb
      data_template:
        brightness_pct: 95
        kelvin: 5000
      
# ##################################
# Master Bedroom Main Lamp (Xiaomi Round LED) - Off
# ##################################
- alias: master_bedroom_main_lamp_off_if_lamp_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d00013e6aa5
        click_type: single
  condition:
    - condition: state
      entity_id: light.round_led_mb
      state: 'on'    
  action:
    - service: light.turn_off
      entity_id: light.round_led_mb

# ##################################
# Master Bedroom Main Lamp (Xiaomi Round LED) - Brightness change with left button 33%
# ##################################
- alias: master_bedroom_main_lamp_on_30_if_lamp_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00013e6aa5
        click_type: single
  condition:
    - condition: state
      entity_id: light.round_led_mb
      state: 'off'    
  action:
    - service: light.turn_on
      entity_id: light.round_led_mb
      data_template:
        brightness_pct: 5
        kelvin: 3000
      
# ##################################
# Master Bedroom Main Lamp (Xiaomi Round LED) - Turn Off with Left Button
# ##################################
- alias: master_bedroom_main_lamp_off_if_lamp_on_with_left_button
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00013e6aa5
        click_type: single
  condition:
    - condition: state
      entity_id: light.round_led_mb
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.round_led_mb
    
# ##################################
# Master Bedroom - Round LED Reset 
# ##################################
- alias: master_bedroom_round_led_reset
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.round_led_mb
      to: 'unavailable'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day_long
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.round_led_mb_restart

# ##################################
# Master Bedroom - Round LED status check
# ##################################
- alias: master_bedroom_round_led_status_check
  initial_state: 'true'
  trigger:
    - platform: time
      at: '07:00:01'
  condition:
    - condition: state
      entity_id: light.round_led_mb
      state: 'unavailable'
  action:
    - service: script.turn_on
      entity_id: script.round_led_mb_restart
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Round LED MB restart done(morning)!"
      
# ##################################
# Master Bedroom - Round LED Power Switch Turn On
# ##################################
- alias: master_bedroom_round_led_switch_on
  initial_state: 'false'
  trigger:
    - platform: state
      entity_id: switch.plug_158d0002482619
      to: 'off'
      for:
        seconds: 3
  action:
    - service: switch.turn_on
      entity_id: switch.plug_158d0002482619
      
# ##################################
# Master Bedroom - Main power turned off
# ##################################
- alias: master_bedroom_main_power_turned_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.wall_plug_158d0002467773
      to: 'off'
      from: 'on'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50c Внимание! Вторая розетка отключена! Запущен UPS (650)"

# ##################################
# Master Bedroom - Main plug pulled out
# ##################################
- alias: master_bedroom_main_plug_pulled_out
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.pc_mb
      below: 10
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50c Внимание! Нагрузка во второй розетке упала! Проверь кабель!"

# ##################################
# Master Bedroom- Main power - over-power
# ##################################
- alias: master_bedroom_big_main_power_overpower
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.pc_mb
      above: 1700 
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50c Внимание! Перегрузка второй розетки! Отключите лишние потребители!"

# ##################################
# Master Bedroom- UPS - OB
# ##################################
- alias: master_bedroom_ups_ob
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.ippon_mb_status_data
      to: 'OB'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50b Внимание! Запущен UPS (650)!"
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "Запущен UPS (650)"

# ##################################
# Master Bedroom- UPS - LB
# ##################################
- alias: master_bedroom_big_ups_lb
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.ippon_mb_status_data
      to: 'LB'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Внимание! Заряд батареи (650) критический! Завершение работы j3455!"
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "UPS полностью разряжен! Завершаем работу j3455!"

# ##################################
# Master Bedroom- UPS - OL
# ##################################
- alias: master_bedroom_ups_ol
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.ippon_mb_status_data
      to: 'OL'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50b Питание восстановлено! Начинаем заряд батареи(650)!"

# ##################################
# Master Bedroom- UPS - Unknown
# ##################################
- alias: master_bedroom_ups_unknown
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.ippon_mb_status_data
      to: "unknown"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Внимание! Связь с UPS(650) потеряна!"

# ##################################
# Master Bedroom- UPS - Unknown to OL
# ##################################
- alias: master_bedroom_ups_unknown_to_ol
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.ippon_mb_status_data
      from: "unknown"
      to: "OL"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50b Связь с UPS(650) восстановлена!"

# ##################################
# Master Bedroom- Main power turned on
# ##################################
- alias: master_bedroom_main_power_turned_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.wall_plug_158d0002467773
      to: 'on'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50c Электроснабжение восстановлено! Начинаем зарядку UPS(650)!"


# # ##################################
# # Master Bedroom - Timer restart with movement
# # ################################## 
# - alias: master_bedroom_timer_restart
#   initial_state: 'true'
#   trigger:
#     - platform: event
#       event_type: xiaomi_aqara.motion
#       event_data:
#         entity_id: binary_sensor.motion_sensor_158d0001e53cda
#   condition:
#     - condition: state
#       entity_id: light.round_led_mb
#       state: 'on'
#   action:
#   - service: timer.cancel
#     entity_id: timer.main_light_mb
#   - service: timer.start
#     entity_id: timer.main_light_mb

# # ##################################
# # Master Bedroom - Timer off
# # ################################## 
# - alias: master_bedroom_timer_off
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: light.round_led_mb
#       to: 'off'
#       from: 'on'
#   action:
#     - service: timer.cancel
#       entity_id: timer.main_light_mb
#     - service: automation.turn_off
#       entity_id: automation.master_bedroom_auto_light_on
#     - delay: '00:00:10'
#     - service: automation.turn_on
#       entity_id: automation.master_bedroom_auto_light_on

# # ##################################
# # Master Bedroom - Timer start on light on
# # ################################## 
# - alias: master_bedroom_timer_on
#   initial_state: 'true'
#   trigger:
#   - platform: state
#     entity_id: light.round_led_mb
#     to: 'on'
#     from: 'off'
#   action:
#     - service: automation.turn_on
#       entity_id: automation.master_bedroom_auto_light_on
#     - service: timer.cancel
#       entity_id: timer.main_light_mb
#     - service: timer.start
#       entity_id: timer.main_light_mb

# # ##################################
# # Master Bedroom - Auto Light Off
# # ##################################
# - alias: master_bedroom_auto_light_off
#   initial_state: 'true'
#   trigger:
#   - platform: event
#     event_type: timer.finished
#     event_data:
#       entity_id: timer.main_light_mb
#   condition:
#     - condition: state
#       entity_id: binary_sensor.tod_day
#       state: 'on'
#   action:
#     - service: light.turn_off
#       entity_id: light.round_led_mb

# ##################################
# Master Bedroom - Auto Light On
# ##################################
# - alias: master_bedroom_auto_light_on
#   initial_state: 'true'
#   trigger:
#     - platform: event
#       event_type: xiaomi_aqara.motion
#       event_data:
#         entity_id: binary_sensor.motion_sensor_158d0001e53cda
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: light.round_led_mb
#         state: 'off'
#       - condition: state
#         entity_id: binary_sensor.tod_day
#         state: 'on'
#       - condition: state
#         entity_id: sun.sun
#         state: below_horizon
#   action:
#     - service: light.turn_on
#       entity_id: light.round_led_mb
      
# ##################################
# Master Bedroom - Auto Ambilight On
# ##################################
# - alias: master_bedroom_auto_ambilight_light
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: light.round_led_mb
#   action:
#     - service: script.turn_on
#       data_template:
#         entity_id: script.master_bedroom_ambilight_{{ states('light.round_led_mb') | lower }}