# #####################################################################################
#
# SASHA
#
# #####################################################################################
# Sasha Table Lamp (Philips E27)
# ##################################
- alias: sasha_table_lamp_on_if_lamp_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001f3627d
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d0003fa6077
        click_type: single
  action:
    - service: light.toggle
      entity_id: light.philips_e27_s

# ##################################        
# Sasha Main Lamp (Xiaomi Round LED) - On
# ##################################
- alias: sasha_main_lamp_on_if_lamp_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d0003fa6077
        click_type: single
  condition:
    - condition: state
      entity_id: light.round_led_s
      state: 'off'    
  action:
    - service: light.turn_on
      entity_id: light.round_led_s
      data_template:
        brightness_pct: 95
        kelvin: 5000
      
# ##################################
# Sasha Main Lamp (Xiaomi Round LED) - Off
# ##################################
- alias: sasha_main_lamp_off_if_lamp_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d0003fa6077
        click_type: single
  condition:
    - condition: state
      entity_id: light.round_led_s
      state: 'on'    
  action:
    - service: light.turn_off
      entity_id: light.round_led_s

# ##################################
# Sasha Table Lamp (Philips E27) - Switch to Bright
# ##################################
- alias: sasha_table_lamp_bright
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001f3627d
        click_type: double
  action:
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_s
      data:
         scene: 1

# ##################################
# Sasha Table Lamp (Philips E27) - Switch to Mid-Night
# ##################################
- alias: sasha_table_lamp_night
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001f3627d
        click_type: long_click_press
  action:
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_s
      data:
        scene: 4

# ##################################
# Sasha - Auto Night Light\Humidifier On
# ##################################
- alias: sasha_auto_nightlight_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d000224f89f
    - platform: event
      event_type: xiaomi_aqara.movement
      event_data:
        entity_id: binary_sensor.vibration_158d0002a8ac3c
        movement_type: vibrate
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'off'
      - condition: state
        entity_id: person.sasha
        state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.philips_e27_s
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_s
      data:
          scene: 4

# ##################################
# Sasha - Humidifier2 State Flag
# ##################################
- alias: sasha_humidifier2_flag
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: fan.humidifier2
      to: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.humidifier2_auto_off

# ##################################
# Sasha - Auto Night Light Off 30m without movements
# ##################################
- alias: sasha_night_auto_off_30m
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000224f89f
      to: 'off'
      for:
        minutes: 30
    - platform: state
      entity_id: binary_sensor.vibration_158d0002a8ac3c
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.philips_e27_s

# ##################################
# Sasha - Night Light On
# ##################################
- alias: sasha_night_light_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00019c8afd
        click_type: single
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.gateway_light_7811dcb8d612
      data:
        brightness: 50
        color_name: white
    - service: light.turn_on
      entity_id: light.philips_e27_s
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_s
      data:
          scene: 4
    - service: light.turn_on
      entity_id: light.led_strip_hb    
      data:
        brightness_pct: 1
        kelvin: 3000
        # rgb_color: [255,255,255]
    - delay: '00:00:30'
    - service: light.turn_off
      entity_id: light.led_strip_hb, light.philips_e27_s, light.gateway_light_7811dcb8d612


#ube	cube	MFKZQ01LM	off (always)	xiaomi_aqara.cube_action	action_type, action_value (rotate)	flip90, flip180, move, tap_twice, shake_air, swing, alert, free_fall, rotate (degrees at action_value)

# ##################################
# Sasha - Cube play 
# ##################################
- alias: sasha_play_night
  initial_state: 'false'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000116b03f
        action_type: shake_air
  condition: 
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.home_mini_s
          state: 'off'
        - condition: state
          entity_id: media_player.home_mini_s
          state: 'idle'
    - condition: time
      after: '07:00'
      before: '06:00'  
  action:
    - service:  media_player.turn_on
      entity_id: media_player.home_mini_s
    - service:  media_player.volume_set
      entity_id: media_player.home_mini_s
      data:
        volume_level: 0.1
    - service: media_player.play_media
      entity_id: media_player.home_mini_s
      data:
        media_content_id: "http://192.168.1.14:8123/local/mp3/goodnight.mp3"
        media_content_type: "audio/mp3"

# ##################################
# Sasha - Cube stop
# ##################################
- alias: sasha_stop_night
  initial_state: 'false'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000116b03f
        action_type: shake_air
  condition: 
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.home_mini_s
          state: 'on'
        - condition: state
          entity_id: media_player.home_mini_s
          state: 'playing'
    - condition: time
      after: '07:00'
      before: '06:00'  
  action:
    - service:  media_player.turn_off
      entity_id: media_player.home_mini_s
#    - service:  media_player.volume_set
#      entity_id: media_player.home_mini_s
#      data:
#        volume_level: 1
#    - service: media_player.play_media
#      entity_id: media_player.home_mini_s
#      data:
#        media_content_id: "http://192.168.1.14:8123/local/goodnight.mp3"
#        media_content_type: "audio/mp3"
      
# ##################################
# Sasha - Humidifier 2 low water notify to Telegram
# ##################################
- alias: sasha_humidifier_water_low_water_cond
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.humidifier_water_level
      below: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.tod_day_long
        state: 'on'
      - condition: state
        entity_id: person.dima
        state: 'home'
  action:
    service: notify.telegram
    data_template:
      message: "\U0001f4a7 Увлажнитель - осталось менее 10% воды!"
      
# ##################################
# Sasha - Humidifier2  Reset
# ##################################
- alias: sasha_humidifier_reset
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: fan.humidifier2
      to: 'unavailable'
      for:
        minutes: 5
  action:
    - service: script.turn_on
      entity_id: script.humidifier2_restart

# ##################################
# Sasha - Round LED Reset 
# ##################################
- alias: sasha_round_led_reset
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.round_led_s
      to: 'unavailable'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day_long
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.round_led_s_restart

# ##################################
# Sasha - Round LED status check
# ##################################
- alias: Sasha_round_led_status_check
  initial_state: 'true'
  trigger:
    - platform: time
      at: '07:00:01'
  condition:
    - condition: state
      entity_id: light.round_led_s
      state: 'unavailable'
  action:
    - service: script.turn_on
      entity_id: script.round_led_s_restart
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Round LED S restart done(morning)!"
        
        
# ##################################
# Sasha - Timer restart with movement
# ################################## 
- alias: sasha_timer_restart
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d000224f89f
  condition:
    - condition: state
      entity_id: light.round_led_s
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_s
    - service: timer.start
      entity_id: timer.main_light_s

# ##################################
# Sasha - Timer off
# ################################## 
- alias: sasha_timer_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.round_led_s
      to: 'off'
      from: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_s
#    - service: automation.turn_off
#      entity_id: automation.sasha_auto_light_on
#    - delay: '00:00:10'
#    - service: automation.turn_on
#      entity_id: automation.sasha_auto_light_on
    
# ##################################
# Sasha - Timer start on light on
# ################################## 
- alias: sasha_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.round_led_s
      to: 'on'
      from: 'off'
  action:
    #- service: automation.turn_on
    #  entity_id: automation.sasha_auto_light_on
    - service: timer.cancel
      entity_id: timer.main_light_s
    - service: timer.start
      entity_id: timer.main_light_s

# ##################################
# Sasha - Auto Light Off
# ##################################
- alias: sasha_auto_light_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.main_light_s
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.round_led_s

# ##################################
# Sasha - Auto Light On
# ##################################
# - alias: sasha_auto_light_on
#   initial_state: 'true'
#   trigger:
#     - platform: event
#       event_type: xiaomi_aqara.motion
#       event_data:
#         entity_id: binary_sensor.motion_sensor_158d000224f89f
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: light.round_led_s
#         state: 'off'
#       - condition: state
#         entity_id: binary_sensor.tod_day
#         state: 'on'
#       - condition: state
#         entity_id: sun.sun
#         state: below_horizon
#   action:
#     - service: light.turn_on
#       entity_id: light.round_led_s
      
# ##################################
# Sasha - Auto Ambilight On
# ##################################
# - alias: sasha_auto_ambilight_light
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: light.round_led_s
#   action:
#     - service: script.turn_on
#       data_template:
#         entity_id: script.sasha_ambilight_{{ states('light.round_led_s') | lower }}
