# ##################################
# Security - Turn  On
# ##################################
- alias: security_turn_on
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.family_home
      to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.security_mode
    state: 'off'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F3e2 Никого нет дома, выключаем освещение!"
    - service: script.lights_off
    - service: notify.telegram
      data_template:
        message: "\U0001f514 Освещение выключено!"
    - service: homeassistant.turn_on
      entity_id: input_boolean.security_mode


# ##################################
# Security - Sensors State change
# ##################################
- alias: security_sensors_state_change
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.security_last_change
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'on'
  action:
    #- service: notify.ios_iphone_8_dtsymbal
    #  data:
    #    title: "Внимание!"
    #    message: "\U0001f46e Обнаружено движение! {{states.sensor.security_last_change.state}}"
    - service: notify.telegram
      data_template:
        message: "\U0001f46e Внимание! Обнаружено движение! {{states.sensor.security_last_change.state}} "


# ##################################
# Security - Turn Off
# ##################################
- alias: security_turn_off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.family_home
      to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.security_mode
      
# ##################################
# Security - Notification
# ##################################
- alias: security_notification
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.security_mode
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f46e Режим охраны {% if states('input_boolean.security_mode') == 'off' %}выключен!{% else %}включен!{% endif %}"


# ##################################
# Security - Presence update on door open
# ##################################
- alias: security_main_door_open_presence_update
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001e5d6be
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.security_mode
    state: 'on'
  action:
    - service: homeassistant.update_entity
      entity_id: person.dima,person.sandra,person.vova,person.sasha