# ##################################
# Security - Turn  On
# ##################################
- alias: security_turn_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.family_home
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'off'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F3e2 Никого нет дома, выключаем освещение!"
    - service: script.turn_on
      entity_id: script.lights_off
    - service: notify.telegram
      data_template:
        message: "\U0001f514 Освещение выключено!"
    - service: homeassistant.turn_on
      entity_id: input_boolean.security_mode
    - service: homeassistant.turn_off
      entity_id: automation.kitchen_auto_light_on, automation.hall_big_auto_light_on #, switch.blackhole_turtle_mode

# ##################################
# Security - Sensors State change
# ##################################
- alias: security_sensors_state_change
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.last_motion
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'on'
  action:
    #- service: notify.notify
    #  data:
    #    title: "Внимание!"
    #    message: "\U0001f46e Обнаружено движение! {{states.sensor.last_motion.state}}"
    - service: notify.telegram
      data_template:
        message: "\U0001f46e Внимание! Обнаружено движение! {{states('sensor.last_motion')}}"


# ##################################
# Security - Turn Off
# ##################################
- alias: security_turn_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.family_home
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.security_mode
    - service: homeassistant.turn_on
      entity_id: automation.kitchen_auto_light_on, automation.hall_big_auto_light_on #, switch.blackhole_turtle_mode 
      
# ##################################
# Security - Notification
# ##################################
- alias: security_notification
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: input_boolean.security_mode
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f46e Режим охраны {% if states('input_boolean.security_mode') == 'off' %}выключен!{% else %}включен!{% endif %}"


# ##################################
# Security - Presence update on door open
# ##################################
- alias: security_main_door_open_presence_update
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0001e5d6be_contact #binary_sensor.door_window_sensor_158d0001e5d6be
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'on'
  action:
    - service: homeassistant.update_entity
      entity_id: person.dima,person.sandra,person.vova,person.sasha, device_tracker.life360_dima_tsymbal,device_tracker.life360_sandra_tsymbal,device_tracker.life360_vova_tsymbal
      

# # ##################################
# # Security - Security system PWR status
# # ##################################
# - alias: security_system_pwr
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.d1_security_power
#   action:
#     - service: notify.telegram
#       data_template:
#         message: "\U0001f693 Охранная система: питание {% if is_state('binary_sensor.d1_security_power','on') %}включено!{% else %}выключено!{% endif %}"

# # ##################################
# # Security - Security system armed
# # ##################################
# - alias: security_system_armed
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.d1_security_armed
#   action:
#     - service: notify.telegram
#       data_template:
#         message: "\U0001f693 Охранная система {% if is_state('binary_sensor.d1_security_armed','on') %}включена!{% else %}выключена!{% endif %}"

# # ##################################
# # Security - Security system alarm
# # ##################################
# - alias: security_system_alarm
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.d1_security_alarm
#   action:
#     - service: notify.telegram
#       data_template:
#         message: "\U0001f693 Охранная система: Тревога {% if is_state('binary_sensor.d1_security_alarm','on') %}включена!{% else %}выключена!{% endif %}"
        
# ##################################
# Security- Main door vibration
# ##################################
- alias: security_main_door_vibration
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.movement
      event_data:
        entity_id: binary_sensor.vibration_158d0002b5fbc1
        movement_type: vibrate
  condition:
    - condition: state
      entity_id: input_boolean.security_mode
      state: 'on'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F6AA Внимание! Главная дверь - Вибрация!"