# #####################################################################################
#
# STORAGE
#
# #####################################################################################
# Storage - Auto Light On
# ##################################
- alias: storage_auto_light_on
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d0001aea602
  action:
  - service: switch.turn_on
    entity_id: switch.wall_switch_158d000248bf53

# ##################################
# Storage - Auto Light On
# ##################################
- alias: storage_light_off
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.timer_st
  action:
  - service: switch.turn_off
    entity_id: switch.wall_switch_158d000248bf53
  - service: timer.cancel
    entity_id: timer.timer_st

# ##################################
# Storage - Timer Start
# ##################################
- alias: storage_timer_start
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.wall_switch_158d000248bf53
    to: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.timer_st
  - service: timer.start
    entity_id: timer.timer_st

# ##################################
# Storage - Timer restart with movement
# ################################## 
- alias: storage_timer_restart
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id:  binary_sensor.motion_sensor_158d0001aea602
  condition:
    - condition: state
      entity_id: switch.wall_switch_158d000248bf53
      state: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.timer_st
  - service: timer.start
    entity_id: timer.timer_st

# ##################################
# Storage - Timer off
# ################################## 
- alias: storage_timer_off
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.wall_switch_158d000248bf53
    to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.timer_st
    - service: automation.turn_off
      entity_id: automation.storage_auto_light_on
    - delay: '00:00:10'
    - service: automation.turn_on
      entity_id: automation.storage_auto_light_on

# ##################################
# Storage - Night Off
# ##################################
- alias: storage_night_off
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00023d0b86
      click_type: single
  action:
    - service: homeassistant.turn_off
      entity_id: light.led_strip_hb, switch.plug_158d0001f5501f, switch.plug_158d000216528c, switch.wall_switch_158d000248bf53, light.gateway_light_7811dcb8cb4b
      
# ##################################
# Storage - Hall big Light Auto turn off
# ##################################
- alias: storage_light_automations_off
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00023d0b86
      click_type: double
  condition:
    - condition: state
      entity_id: automation.hall_big_auto_light_on
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.hall_big_auto_light_on
    - delay: '01:00:00'
    - service: homeassistant.turn_on
      entity_id: automation.hall_big_auto_light_on
      
# ##################################
# Storage - Hall big Light Auto turn on
# ##################################
- alias: storage_light_automations_on
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00023d0b86
      click_type: double
  condition:
    - condition: state
      entity_id: automation.hall_big_auto_light_on
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: automation.hall_big_auto_light_on
