# #####################################################################################
#
# SYSTEM TASKS
#
# #####################################################################################

# ##################################
# System - Adguard state
# ##################################
- alias: system_adguard_state
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.adguard_protection
    - platform: state
      entity_id: binary_sensor.adguard_runnig
  action:
    - service: notify.telegram
      data_template:
        message: "AdGuard state - {{states.binary_sensor.adguard_runnig.state | upper}}, protection - {{states.binary_sensor.adguard_protection.state | upper}}!"

# ##################################
# System - Window Cam Snapshot on Motion
# ##################################
- alias: system_window_snapshot
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.unifi_motion_window
    from: 'off'
    to: 'on'
  action:
    - delay: "00:00:01"
    - service: camera.snapshot
      data:
        entity_id: camera.uvc_g3_flex_window
        filename: "/config/www/cam_captures/window.jpg"
    - service: notify.telegram_cam
      data:
        title: "{{now().strftime('%H:%M %d-%m-%Y')}}"
        message: "{{now().strftime('%H:%M %d-%m-%Y')}}"
        data:
          photo:
          - file: "/config/www/cam_captures/window.jpg"
            caption: "{{now().strftime('%H:%M %d-%m-%Y')}}"

# ##################################
# System - Errors counter
# ##################################
- alias: system_error_counter
  initial_state: 'on'
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
        level: ERROR
  action:
    - service: counter.increment
      entity_id: counter.error_counter

# ##################################
# System - Warning counter
# ##################################
- alias: system_warning_counter
  initial_state: 'on'
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: WARNING
  action:
    service: counter.increment
    entity_id: counter.warning_counter

# ##################################
# System - START message
# ##################################
- alias: system_start_message
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F603 Сервер запущен!"
    - service: script.system_start
    - service: counter.increment
      entity_id: counter.restart_counter
    
# ##################################
# System - STOP message
# ##################################
- alias: system_stop_message
  initial_state: 'on'
  trigger:
    platform: event
    event_type: homeassistant_stop
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F621 Сервер остановлен!"
        
# ##################################
# System - Radio Volume
# ##################################
- alias: system_set_radio_volume
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.chromecast_radio", "Kitchen") %} media_player.home_mini_k
        {% elif is_state("input_select.chromecast_radio", "Vova's room") %} media_player.home_mini_v
        {% elif is_state("input_select.chromecast_radio", "Sasha's room") %} media_player.home_mini_s
        {% elif is_state("input_select.chromecast_radio", "Master Bedroom") %} media_player.home_mini_mb
        {% elif is_state("input_select.chromecast_radio", "Hall big") %} media_player.mpd
        {% elif is_state("input_select.chromecast_radio", "Everywhere") %} media_player.all_speakers
        {% endif %}
      volume_level: '{{  states.input_number.volume_radio.state  }}' 


# ##################################
# System - Ubuntu server CPU temp >65
# ##################################
- alias: system_server_cpu_temp_high
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temperature
    above: 65
    for:
      minutes: 5
  action:
    - service: notify.ios_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "Температура процессора сервера превысила 65°"
    - service: notify.telegram
      data:
        message: "\U0001F525 Внимание! Температура процессора сервера превысила 65°"

# ##################################
# System - Hass.io NEW Device
# ##################################
- alias: system_new_device_found
  initial_state: 'on'
  trigger:
    platform: event
    event_type:  device_tracker_new_device
  action:
    - service: notify.telegram
      data_template: 
        message: "\U00002734 Новое устройство: {{ trigger.event.data.host_name if trigger.event.data.host_name is defined else 'NA' }} - ({{ trigger.event.data.entity_id if trigger.event.data.entity_id is defined else 'NA' }})"

# ##################################
# System - Hass.io NEW Version
# ##################################
- alias: system_hassio_new_version
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.telegram
    data_template: 
      message: "\U00002733 {{ states.updater.updater.state }} доступен!"

# ##################################
# System - NEW DAY
# ##################################
- alias: system_new_day_telegramm
  initial_state: 'on'
  trigger:
    platform: time
    at: '00:00:01'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F305 Начался новый день! За прошедшие сутки перезагрузок - {{states.counter.restart_counter.state}}, ошибок - {{states.counter.error_counter.state}}, предупреждений - {{states.counter.warning_counter.state}}, ошибок входа - {{states.counter.badlogin_counter.state}}. Входная дверь открывалась - {{states.counter.main_door_hb.state}} р."
    - service: counter.reset
      entity_id: counter.warning_counter, counter.error_counter, counter.restart_counter, counter.badlogin_counter, counter.main_door_hb
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.weather_announcement_flag

# ##################################
# System - Weather FCST to Telegram
# ##################################
- alias: system_weather_to_telegram
  initial_state: 'on'
  trigger:
    - platform: time
      at: '17:00:00'
    - platform: time
      at: '21:00:00'
  action:
  - service: script.telegram_weather

# ##################################
# System - Dima At home
# ##################################
- alias: system_presence_dima_at_home
  initial_state: 'on'
  trigger:
    - platform: state
      #entity_id: device_tracker.life360_dima_tsymbal
      entity_id: person.dima
      to: "home"
      for: 00:03:00
  action: 
    - service: notify.telegram
      data_template:
        message: "\U0001F9D4 Дима дома!"
        
# ##################################
# System - Vova At home
# ##################################
- alias: system_presence_vova_at_home
  initial_state: 'on'
  trigger:
    - platform: state
      #entity_id: device_tracker.life360_vova_tsymbal
      entity_id: person.vova
      to: "home"
      for: 00:03:00
  action: 
    - service: notify.telegram
      data_template:
        message: "\U0001F471 Вова дома!"

# ##################################
# System - Sandra At home
# ##################################
- alias: system_presence_sandra_at_home
  initial_state: 'on'
  trigger:
    - platform: state
      #entity_id: device_tracker.life360_sandra_tsymbal
      entity_id: person.sandra
      to: "home"
      for: 00:03:00
  action: 
    - service: notify.telegram
      data_template:
        message: "\U0001F467 Саша дома!"

# ##################################
# System - Sasha At home
# ##################################
#- alias: system_presence_sasha_at_home
#  initial_state: 'on'
#  trigger:
#    - platform: state
#      #entity_id: device_tracker.life360_sandra_tsymbal
#      entity_id: person.sasha
#      to: "home"
#  action: 
#    - service: notify.telegram
#      data_template:
#        message: "\U0001F467 Санек дома!"


# ##################################
# System - login failure message
# ##################################
- alias: system_login_failure
  initial_state: 'on'
  hide_entity: false
  trigger:
    - platform: state
      entity_id: persistent_notification.http_login
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != off }}"
  action:
    - service: counter.increment
      entity_id: counter.badlogin_counter
    - service: notify.telegram
      data_template:
        message: "\U0000274C Неудачная попытка подлючения. Неверно введен пароль! {{ states.persistent_notification.http_login.attributes.message }}"
    - service: persistent_notification.dismiss
      data:
        notification_id: http_login

# ##################################
# System - Sasha tracker - Toggle
# ##################################
- alias: system_sasha_tracker_toggle
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001ef6089
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001ef6089
        click_type: double
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.sasha_tracker

# ##################################
# System - Sasha tracker
# ##################################
- alias: system_sasha_tracker
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.sasha_tracker
    #from: "off"
    #to: "on"
  action:
    - service: device_tracker.see
      data_template:
        dev_id: sasha
        location_name: "{% if is_state('input_boolean.sasha_tracker','on')%}home{%else%}not_home{%endif%}"

# ##################################
# System - Sasha tracker - Audio
# ##################################
- alias: system_sasha_audio_tts
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.sasha_tracker
    #from: 'on'
    #to: 'off'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:00:00'
        before: '21:00:00'
      - condition: template
        value_template: "{{ as_timestamp(now()) - as_timestamp(states.binary_sensor.switch_158d0001ef6089.last_changed) < 10 }}"
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.mpd
        volume_level: '0.3'
    - service: tts.yandextts_say
      entity_id: media_player.mpd
      data_template:
        message: >
          {% set name1 = ['С+аша, ','Сан+ёк, ','Алекс+андр, ','М+итрич, ','Алекс+андр Дм+итриевич, '] | random %}
          {% set greet2  = ['пок+а!','до свид+ания!','до встр+ечи!','чава-как+ава!','всег+о хор+ошего!'] | random %}
          {% set greet1 = ['прив+ет!','здар+ова!','здр+авствуй!','здр+авия жел+аю!','сал+ют!'] | random %}
          
          {{name1}} {% if is_state('input_boolean.sasha_tracker','on')%}{{greet1}}{%else%}{{greet2}}{%endif%}
    - service: notify.telegram
      data_template:
        message: "\U0001F476 Санек {%if is_state('input_boolean.sasha_tracker','on')%}дома{%else%}уходит{%endif%}!"
