# ##################################
# System - Ubuntu server CPU temp >60
# ##################################
- alias: system_health_temp
  initial_state: 'true'
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.ipmi_cpu_temp
      - sensor.ipmi_dimma1_temp
      - sensor.ipmi_dimmb1_temp
      - sensor.ipmi_dimmc1_temp
      - sensor.ipmi_dimmd1_temp
      - sensor.ipmi_peripheral_temp
      - sensor.ipmi_vcpuvrm_temp
      - sensor.ipmi_vmemabvrm_temp
      - sensor.ipmi_vmemcdvrm_temp
      - sensor.ipmi_cpu_temp
      - sensor.ipmi_pch_temp
      - sensor.ipmi_system_temp
    above: 60
    for:
      minutes: 3
  action:
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "{{ trigger.to_state.attributes.friendly_name }} >60°"
    - service: notify.telegram
      data:
        message: "\U0001F525 Внимание! {{ trigger.to_state.attributes.friendly_name }} >60°"

# ##################################
# System - server root device
# ##################################
- alias: system_health_rdev
  initial_state: 'false'
  trigger:
    - platform: template
      value_template: "{% if states('sensor.root_device') != '/dev/sda2' %}true{% endif %}"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F621 Внимание! Root устройство изменено!"

# ##################################
# System - MDADM status change
# ##################################
- alias: system_health_mdadm_monitor
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id:
        - sensor.md0_status
        - sensor.md1_status
        - sensor.md2_status
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f4ab {{ trigger.from_state.attributes.friendly_name }} from {{trigger.from_state.state}} to {{trigger.to_state.state}}"
        
# ##################################
# System - Server HDD Disks Temp
# ##################################
- alias: system_health_hdd_temp
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.sda_temp
        - sensor.sdb_temp
        - sensor.sdc_temp
        - sensor.sdd_temp
        - sensor.sdf_temp
        - sensor.sdg_temp
        - sensor.sdh_temp
        - sensor.media1_temp
        - sensor.media2_temp
        - sensor.temp_temp
      above: 40
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >40°!"

# ##################################
# System - Server SSD Disks Temp
# ##################################
- alias: system_health_ssd_temp_50
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.nvme0_temp
        - sensor.nvme1_temp
        - sensor.nvme2_temp
        - sensor.nvme3_temp
        - sensor.nvme4_temp
        - sensor.boot_temp
        - sensor.840pro_1_temp
        - sensor.840pro_2_temp
      above: 50
      for:
        minutes: 3
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >50°!"

# ##################################
# System - Server SSD Disks Temp
# ##################################
- alias: system_health_ssd_temp_55
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.nvme0_temp
        - sensor.nvme1_temp
        - sensor.nvme2_temp
        - sensor.nvme3_temp
        - sensor.nvme4_temp
        - sensor.boot_temp
        - sensor.840pro_1_temp
        - sensor.840pro_2_temp
      above: 55
      for:
        minutes: 3
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >55°!"
        
# ##################################
# System - Server SSD Disks Temp
# ##################################
- alias: system_health_ssd_temp_60
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.nvme0_temp
        - sensor.nvme1_temp
        - sensor.nvme2_temp
        - sensor.nvme3_temp
        - sensor.nvme4_temp
        - sensor.boot_temp
        - sensor.840pro_1_temp
        - sensor.840pro_2_temp
      above: 60
      for:
        minutes: 1
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >60°!"

# ##################################
# System - Server Fans stats
# ##################################
- alias: system_health_fans
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.ipmi_fan1
        - sensor.ipmi_fan2
        - sensor.ipmi_fan3
        - sensor.ipmi_fan4
        - sensor.ipmi_fan5
        - sensor.ipmi_fana
      below: 250
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f300 Внимание! {{ trigger.to_state.attributes.friendly_name }} < 250об!"


# ##################################
# System - System Monitoring Update
# ##################################
- alias: system_health_monitoring_update
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/30"
  action:
    - service: homeassistant.update_entity
      entity_id: 
        - sensor.nvme0_calc_life_left
        - sensor.nvme0_gb_per_day
        - sensor.nvme0_gb_per_hour
        - sensor.nvme0_life_left
        - sensor.nvme0_power_on_hours
        - sensor.nvme0_session_read
        - sensor.nvme0_session_write
        - sensor.nvme0_statistics
        - sensor.nvme0_tb_written
        - sensor.nvme0_temp
        - sensor.nvme0_usage
        - sensor.nvme0_write_change_1h
        
        - sensor.nvme1_gb_per_day
        - sensor.nvme1_gb_per_hour
        - sensor.nvme1_life_left
        - sensor.nvme1_power_on_hours
        - sensor.nvme1_session_read
        - sensor.nvme1_session_write
        - sensor.nvme1_statistics
        - sensor.nvme1_tb_written
        - sensor.nvme1_temp
        - sensor.nvme1_usage
        - sensor.nvme1_write_change_1h
        
        - sensor.nvme2_gb_per_day
        - sensor.nvme2_gb_per_hour
        - sensor.nvme2_life_left
        - sensor.nvme2_power_on_hours
        - sensor.nvme2_session_read
        - sensor.nvme2_session_write
        - sensor.nvme2_statistics
        - sensor.nvme2_tb_written
        - sensor.nvme2_temp
        - sensor.nvme2_usage
        - sensor.nvme2_write_change_1h

        - sensor.nvme3_gb_per_day
        - sensor.nvme3_gb_per_hour
        - sensor.nvme3_life_left
        - sensor.nvme3_power_on_hours
        - sensor.nvme3_session_read
        - sensor.nvme3_session_write
        - sensor.nvme3_statistics
        - sensor.nvme3_tb_written
        - sensor.nvme3_temp
        - sensor.nvme3_usage
        - sensor.nvme3_write_change_1h

        - sensor.nvme4_gb_per_day
        - sensor.nvme4_gb_per_hour
        - sensor.nvme4_life_left
        - sensor.nvme4_power_on_hours
        - sensor.nvme4_session_read
        - sensor.nvme4_session_write
        - sensor.nvme4_statistics
        - sensor.nvme4_tb_written
        - sensor.nvme4_temp
        - sensor.nvme4_usage
        - sensor.nvme4_write_change_1h
        
        - sensor.boot_gb_per_day
        - sensor.boot_gb_per_hour
        - sensor.boot_life_left
        - sensor.boot_power_on_hours
        - sensor.boot_session_read
        - sensor.boot_session_write
        - sensor.boot_statistics
        - sensor.boot_tb_written
        - sensor.boot_temp
        - sensor.boot_write_change_1h
        
        - sensor.840pro_1_calc_life_left
        - sensor.840pro_1_gb_per_day
        - sensor.840pro_1_gb_per_hour
        - sensor.840pro_1_life_left
        - sensor.840pro_1_power_on_hours
        - sensor.840pro_1_session_read
        - sensor.840pro_1_session_write
        - sensor.840pro_1_statistics
        - sensor.840pro_1_tb_written
        - sensor.840pro_1_temp
        - sensor.840pro_1_usage
        - sensor.840pro_1_write_change_1h

        - sensor.840pro_2_calc_life_left
        - sensor.840pro_2_gb_per_day
        - sensor.840pro_2_gb_per_hour
        - sensor.840pro_2_life_left
        - sensor.840pro_2_power_on_hours
        - sensor.840pro_2_session_read
        - sensor.840pro_2_session_write
        - sensor.840pro_2_statistics
        - sensor.840pro_2_tb_written
        - sensor.840pro_2_temp
        - sensor.840pro_2_usage
        - sensor.840pro_2_write_change_1h