# #####################################################################################
#
# SYSTEM TASKS
#
# #####################################################################################

# ##################################
# System - Adguard state
# ##################################
#- alias: system_adguard_state
#  initial_state: 'off'
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.adguard_protection
#    - platform: state
#      entity_id: binary_sensor.adguard_runnig
#  action:
#    - service: notify.telegram
#      data_template:
#        message: "AdGuard state - {{states.binary_sensor.adguard_runnig.state | upper}}, protection - {{states.binary_sensor.adguard_protection.state | upper}}!"

# ##################################
# System - Window Cam Snapshot on Motion
# ##################################
- alias: system_window_snapshot
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.unifi_motion_window
    from: 'off'
    to: 'on'
  action:
    - delay: '00:00:01'
    - service: camera.snapshot
      data:
        entity_id: camera.uvc_g3_flex_window
        filename: "/config/www/cam_captures/window.jpg"
    - delay: '00:00:01'
    - service: notify.telegram_cam
      data:
        title: "{{states('sensor.time')}} {{states('sensor.date')}}"
        message: "{{states('sensor.time')}} {{states('sensor.date')}}"
        data:
          photo:
          - file: "/config/www/cam_captures/window.jpg"
            caption: "{{states('sensor.time')}} {{states('sensor.date')}}"

# ##################################
# System - Errors counter
# ##################################
- alias: system_error_counter
  initial_state: 'on'
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
        level: ERROR
  action:
    - service: counter.increment
      entity_id: counter.error_counter

# ##################################
# System - Warning counter
# ##################################
- alias: system_warning_counter
  initial_state: 'on'
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: WARNING
  action:
    service: counter.increment
    entity_id: counter.warning_counter

# ##################################
# System - START message
# ##################################
- alias: system_start_message
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F603 Сервер запущен!"
    - service: automation.trigger
      entity_id: automation.system_sasha_tracker
    - service: script.turn_on
      entity_id: script.system_start
    - service: counter.increment
      entity_id: counter.restart_counter
    
# ##################################
# System - STOP message
# ##################################
- alias: system_stop_message
  initial_state: 'on'
  trigger:
    platform: event
    event_type: homeassistant_stop
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F621 Сервер остановлен!"
        
# ##################################
# System - Radio Volume
# ##################################
- alias: system_set_radio_volume
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.chromecast_radio", "Kitchen GHM") %} media_player.home_mini_k
        {% elif is_state("input_select.chromecast_radio", "Vova's room GHM") %} media_player.home_mini_v
        {% elif is_state("input_select.chromecast_radio", "Sasha's room GHM") %} media_player.home_mini_s
        {% elif is_state("input_select.chromecast_radio", "Master Bedroom GHM ") %} media_player.home_mini_mb
        {% elif is_state("input_select.chromecast_radio", "Hall big") %} media_player.mpd
        {% elif is_state("input_select.chromecast_radio", "Hall big GHM") %} media_player.home_mini_hb
        {% elif is_state("input_select.chromecast_radio", "Everywhere") %} media_player.all_speakers
        {% endif %}
      volume_level: "{{ states('input_number.volume_radio') }}"


# ##################################
# System - Ubuntu server CPU temp >65
# ##################################
- alias: system_server_cpu_temp_high
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temperature
    above: 60
    for:
      minutes: 5
  action:
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "Температура процессора сервера превысила 65°"
    - service: notify.telegram
      data:
        message: "\U0001F525 Внимание! Температура процессора сервера превысила 65°"

# ##################################
# System - Hass.io NEW Device
# ##################################
- alias: system_new_device_found
  initial_state: 'on'
  trigger:
    platform: event
    event_type:  device_tracker_new_device
  action:
    - service: notify.telegram
      data_template: 
        message: "\U00002734 Новое устройство: {{ trigger.event.data.host_name if trigger.event.data.host_name is defined else 'NA' }} - ({{ trigger.event.data.entity_id if trigger.event.data.entity_id is defined else 'NA' }})"

# ##################################
# System - Hass.io NEW Version
# ##################################
- alias: system_hassio_new_version
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.update_available 
      from: 'off'
      to: 'on'
  action:
    service: notify.telegram
    data_template: 
      message: "\U00002733 Hass.io {{states('sensor.ha_latest_version')}} доступен!"

# ##################################
# System - NEW DAY
# ##################################
- alias: system_new_day_telegram
  initial_state: 'on'
  trigger:
    - platform: time
      at: '00:00:02'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F305 Начался новый день! За прошедшие сутки перезагрузок - {{states('counter.restart_counter')|int }}, ошибок - {{states('counter.error_counter')|int }}, предупреждений - {{states('counter.warning_counter')|int}}, ошибок входа - {{states('counter.badlogin_counter')|int}}. Входная дверь открывалась - {{states('counter.main_door_hb')|int}}раз(а)."
    - service: counter.reset
      entity_id: counter.warning_counter, counter.error_counter, counter.restart_counter, counter.badlogin_counter, counter.main_door_hb
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.weather_announcement_flag

# ##################################
# System - Weather FCST to Telegram
# ##################################
- alias: system_weather_to_telegram
  initial_state: 'on'
  trigger:
    - platform: time
      at: '07:00:00'
    #- platform: time
    #  at: '17:00:00'
    - platform: time
      at: '21:00:00'
  action:
  - service: script.turn_on
    entity_id: script.weather_telegram

# ##################################
# System - Dima At home
# ##################################
- alias: system_presence_dima_at_home
  initial_state: 'on'
  trigger:
    - platform: state
      #entity_id: device_tracker.life360_dima_tsymbal
      entity_id: person.dima
      to: "home"
      for: 00:03:00
  action: 
    - service: notify.telegram
      data_template:
        message: "\U0001F9D4 Дима дома!"
        
# ##################################
# System - Vova At home
# ##################################
- alias: system_presence_vova_at_home
  initial_state: 'on'
  trigger:
    - platform: state
      #entity_id: device_tracker.life360_vova_tsymbal
      entity_id: person.vova
      to: "home"
      for: 00:03:00
  action: 
    - service: notify.telegram
      data_template:
        message: "\U0001F471 Вова дома!"

# ##################################
# System - Sandra At home
# ##################################
- alias: system_presence_sandra_at_home
  initial_state: 'on'
  trigger:
    - platform: state
      #entity_id: device_tracker.life360_sandra_tsymbal
      entity_id: person.sandra
      to: "home"
      for: 00:03:00
  action: 
    - service: notify.telegram
      data_template:
        message: "\U0001F467 Саша дома!"

# ##################################
# System - Sasha At home
# ##################################
#- alias: system_presence_sasha_at_home
#  initial_state: 'on'
#  trigger:
#    - platform: state
#      #entity_id: device_tracker.life360_sandra_tsymbal
#      entity_id: person.sasha
#      to: "home"
#  action: 
#    - service: notify.telegram
#      data_template:
#        message: "\U0001F467 Санек дома!"


# ##################################
# System - login failure message
# ##################################
- alias: system_login_failure
  initial_state: 'on'
  hide_entity: false
  trigger:
    - platform: state
      entity_id: persistent_notification.http_login
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != off }}"
  action:
    - service: counter.increment
      entity_id: counter.badlogin_counter
    - service: notify.telegram
      data_template:
        message: "\U0000274C Неудачная попытка подлючения. Неверно введен пароль! {{ state_attr('persistent_notification.http_login','message') }}"
    - service: persistent_notification.dismiss
      data:
        notification_id: http_login

# ##################################
# System - Sasha tracker - Toggle
# ##################################
- alias: system_sasha_tracker_toggle
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0002fa99a8
        click_type: single
#    - platform: event
#      event_type: xiaomi_aqara.click
#      event_data:
#        entity_id: binary_sensor.switch_158d0002fa99a8
#        click_type: double
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.sasha_tracker

# ##################################
# System - Sasha tracker
# ##################################
- alias: system_sasha_tracker
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.sasha_tracker
  action:
    - service: device_tracker.see
      data_template:
        dev_id: sasha
        location_name: "{% if is_state('input_boolean.sasha_tracker','on')%}home{%else%}not_home{%endif%}"

# ##################################
# System - Sasha tracker - Audio
# ##################################
- alias: system_sasha_audio_tts
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.sasha_tracker
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:00:00'
        before: '21:00:00'
      #- condition: template
      #  value_template: '{{ as_timestamp(now()) - as_timestamp(states.binary_sensor.switch_158d0002fa99a8.last_changed) < 20 }}'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.mpd
        volume_level: '0.3'
    - service: tts.yandextts_say
      entity_id: media_player.mpd
      data_template:
        message: >
          {% set name1 = ['С+аша, ','Сан+ёк, ','Алекс+андр, ','М+итрич, ','Алекс+андр Дм+итриевич, ', 'М+аленький хоз+яин, '] | random %}
          {% set greet2  = ['пок+а!','до свид+ания!','до встр+ечи!','чава-как+ава!','всег+о хор+ошего!', 'я б+уду скуч+ать!'] | random %}
          {% set greet1 = ['прив+ет!','здар+ова!','здр+авствуй!','здр+авия жел+аю!','сал+ют!',' Ур+а! Ур+а! Ты верн+улся дом+ой!'] | random %}
          
          {{name1}} {% if is_state('input_boolean.sasha_tracker','on')%}{{greet1}}{%else%}{{greet2}}{%endif%}
    - service: notify.telegram
      data_template:
        message: "\U0001F476 Санек {%if is_state('input_boolean.sasha_tracker','on')%}дома{%else%}уходит{%endif%}!"

# ##################################
# System - Sensors Low Battery Notification
# ##################################
- alias: system_low_battery
  initial_state: 'on'
  trigger:
    platform: numeric_state
    value_template: '{{ state.attributes.battery_level }}'
    below: 9
    above: 11
    entity_id:
      # HALL BIG
      - binary_sensor.switch_158d0002fa99a8
      - binary_sensor.door_window_sensor_158d000253722b
      - binary_sensor.door_window_sensor_158d000252acba
      - sensor.temperature_158d0002461e5b
      - sensor.temperature_158d0002464ec0
      - binary_sensor.motion_sensor_158d0001d5995e
      - binary_sensor.door_window_sensor_158d0001e5d6be
      - binary_sensor.door_window_sensor_158d0002531749
      - binary_sensor.motion_sensor_158d0001e05856
      - binary_sensor.motion_sensor_158d0002b482e9
      - binary_sensor.switch_158d00023d3206
      - binary_sensor.vibration_158d0002a2412d
      - sensor.humidity_158d000237167c
      - binary_sensor.door_window_sensor_158d0002a1a4b2
      - binary_sensor.door_window_sensor_158d0002b7c2c8
      # HALL SMALL
      - binary_sensor.motion_sensor_158d0001ae9f61
      - binary_sensor.wall_switch_right_158d00026ea94e
      - binary_sensor.motion_sensor_158d0002b48381
      # KITCHEN
      - binary_sensor.door_window_sensor_158d00025371f6
      - binary_sensor.water_leak_sensor_158d00023297e7
      - sensor.temperature_158d0001e586af
      - binary_sensor.motion_sensor_158d0002b4729d
      - binary_sensor.switch_158d0001ef61be
      - binary_sensor.switch_158d0001ef609b
      - binary_sensor.switch_158d00023e5f2a
      - switch.wall_switch_right_158d0002a365df
      - binary_sensor.door_window_sensor_158d0002a1a47a
      # MASTER BEDROOM
      - binary_sensor.door_window_sensor_158d000200ad58
      - binary_sensor.door_window_sensor_158d00025315e9
      - binary_sensor.motion_sensor_158d0001e53cda
      - binary_sensor.wall_switch_both_158d00013e6aa5
      - sensor.temperature_158d000222c746
      - binary_sensor.switch_158d00023d3116
      - sensor.temperature_158d0001e8995a
      # VOVA
      - binary_sensor.door_window_sensor_158d00022ccffe
      - binary_sensor.door_window_sensor_158d0002529b9c
      - binary_sensor.motion_sensor_158d000236bb94
      - binary_sensor.switch_158d00016bdb4a
      - binary_sensor.wall_switch_both_158d0001712d55
      - sensor.temperature_158d0001e58714
      - binary_sensor.wall_switch_both_158d00026eb820
      - binary_sensor.door_window_sensor_158d000236fdc9
      # STORAGE
      - binary_sensor.motion_sensor_158d0001aea602
      - binary_sensor.switch_158d00023d0b86
      - sensor.temperature_158d000233fb72
      # BATHROOM
      - switch.plug_158d0001f9ebd8
      - binary_sensor.door_window_sensor_158d0002a14c5e
      - binary_sensor.motion_sensor_158d000236bc6d
      - binary_sensor.water_leak_sensor_158d0002373a67
      - sensor.temperature_158d00020d7c3a
      - binary_sensor.door_window_sensor_158d000236fcd5
      # TOILET
      - binary_sensor.door_window_sensor_158d0001ef2ffc
      - binary_sensor.motion_sensor_158d0001e54280
      - binary_sensor.switch_158d0001b97111
      - binary_sensor.water_leak_sensor_158d00023684c2
      - sensor.temperature_158d0001e58754
      - binary_sensor.door_window_sensor_158d000232ddd6
      - binary_sensor.door_window_sensor_158d000232de79
      # SASHA
      - binary_sensor.cube_158d000116b03f
      - binary_sensor.door_window_sensor_158d00025370d1
      - binary_sensor.door_window_sensor_158d00027129ae
      - binary_sensor.motion_sensor_158d000224f89f
      - binary_sensor.switch_158d00019c8afd
      - binary_sensor.switch_158d0001f3627d
      - binary_sensor.vibration_158d0002a8ac3c
      - sensor.temperature_158d0001e6d85a
  action:  
  - service: notify.telegram
    data_template:           
      message: "\U0001f6a8 Low battery level: {{ trigger.to_state.name }} - {{ trigger.to_state.attributes.battery_level }}%"

# ##################################      
# System - Tor restart every 2 hours
# ##################################
- alias: system_tor_restart
  initial_state: 'off'
  trigger:
    platform: time_pattern
    hours: '/2'
  action:
    - service: hassio.addon_restart
      data:
        addon: "a0d7b954_tor"
        
# ##################################
# System - server root device
# ##################################
- alias: system_rdev
  initial_state: 'off'
  trigger:
    - platform: template
      value_template: "{% if states('sensor.root_device') != '/dev/sda2' %}true{% endif %}"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F621 Внимание! Root устройство изменено!"

# ##################################
# System - Home weather (ya)
# ##################################
- alias: system_weather_home
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: sensor.ya_weather_home
  condition:
    - condition: time
      after: "07:00:00"
      before: "21:00:00"
  action:
    - service: notify.telegram_family
      data_template:
        message: "\U00002602 Погода дома: {{states('sensor.ya_weather_home')}}"

# ##################################
# System - Outside motion
# ##################################
- alias: system_motion_outside
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.doorcam_email_unread
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.motion_out
    - delay: '00:00:05'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.motion_out

# ##################################
# System - Person State
# ##################################
#- alias: system_person_state
#  initial_state: 'on'
#  trigger:
#    - platform: state
#      entity_id: person.dima
#    - platform: state
#      entity_id: person.sandra
#    - platform: state
#      entity_id: person.vova
#    - platform: state
#      entity_id: person.sasha
#  condition:
#    - condition: template
#      value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
   # condition: and
  #  conditions:
 #   
  #    
      #- condition: template
      #  value_template: "{{ not is_state('trigger.from_state.state','not_home') }}"
      #- condition: template
      #  value_template: "{{ not is_state('trigger.to_state.state','not_home') }}"
#  action:
#    - service: notify.telegram
#      data_template:
#        message: "{%if trigger.from_state.attributes.friendly_name =='Dima'%}\U0001F9D4 Дима: {%elif trigger.from_state.attributes.friendly_name =='Sandra'%}\U0001F467 Саша: {%elif trigger.from_state.attributes.friendly_name =='Vova'%}\U0001F471 Вова: {%elif trigger.from_state.attributes.friendly_name =='Sasha'%}\U0001F476 Санек: {%endif%} {{ trigger.to_state.state|capitalize }}"
#        {{ trigger.from_state.state|capitalize }} ->
