# ##################################
# System - Ubuntu server CPU temp >60
# ##################################
- alias: system_health_temp
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.ipmi_cpu1_temp
      #- sensor.ipmi_cpu2_temp
      - sensor.ipmi_tr1_temp
      - sensor.ipmi_tr2_temp
    above: 60
    for:
      minutes: 3
  action:
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "{{ trigger.to_state.attributes.friendly_name }} >60°"
    - service: notify.telegram
      data:
        message: "\U0001F525 Внимание! {{ trigger.to_state.attributes.friendly_name }} >60°"

# ##################################
# System - server root device
# ##################################
- alias: system_health_rdev
  initial_state: 'off'
  trigger:
    - platform: template
      value_template: "{% if states('sensor.root_device') != '/dev/sda2' %}true{% endif %}"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001F621 Внимание! Root устройство изменено!"

# ##################################
# System - MDADM status change
# ##################################
- alias: system_health_mdadm_monitor
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.md0_status
        - sensor.md1_status
        - sensor.md2_status
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f4ab {{ trigger.from_state.attributes.friendly_name }} from {{trigger.from_state.state}} to {{trigger.to_state.state}}"
        
# ##################################
# System - Server HDD Disks Temp
# ##################################
- alias: system_health_hdd_temp
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.sdc_temp
        - sensor.sdd_temp
        - sensor.sde_temp
        - sensor.sdf_temp
        - sensor.sdg_temp
        - sensor.sdh_temp
        - sensor.sdi_temp
        - sensor.sdj_temp
        - sensor.sdk_temp
        - sensor.sdl_temp
        - sensor.sdm_temp
      above: 40
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >40°!"

# ##################################
# System - Server SSD Disks Temp
# ##################################
- alias: system_health_ssd_temp_50
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.nvme0_temp
        - sensor.nvme1_temp
        - sensor.nvme2_temp
        - sensor.sda_temp
        - sensor.sdb_temp
      above: 50
      for:
        minutes: 3
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >50°!"

# ##################################
# System - Server SSD Disks Temp
# ##################################
- alias: system_health_ssd_temp_55
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.nvme0_temp
        - sensor.nvme1_temp
        - sensor.nvme2_temp
        - sensor.sda_temp
        - sensor.sdb_temp
      above: 55
      for:
        minutes: 3
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >55°!"
        
# ##################################
# System - Server SSD Disks Temp
# ##################################
- alias: system_health_ssd_temp_60
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.nvme0_temp
        - sensor.nvme1_temp
        - sensor.nvme2_temp
        - sensor.sda_temp
        - sensor.sdb_temp
      above: 60
      for:
        minutes: 1
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f321 Внимание! {{ trigger.to_state.attributes.friendly_name }} >60°!"


        
# ##################################
# System - Server Fans stats
# ##################################
- alias: system_health_fans
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.ipmi_front_fan_1
        - sensor.ipmi_front_fan_2
        - sensor.ipmi_front_fan_3
        - sensor.ipmi_front_fan_4
        - sensor.ipmi_front_rear_1
        - sensor.ipmi_front_rear_2
        - sensor.ipmi_cpu_fan1
        #- sensor.ipmi_cpu_fan2
      below: 300
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f300 Внимание! {{ trigger.to_state.attributes.friendly_name }} < 300об!"