# #####################################################################################
#
# TOILET
#
# #####################################################################################
# Toilet Fan - On 10m
# ##################################
- alias: toilet_fan_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b97111
        click_type: single
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000232ddd6
      to: 'off'
      for: 
        minutes: 2
  action:
    - service: switch.turn_on
      entity_id: switch.plug_158d0001f54f91

# ##################################
# Toilet Fan - On
# ##################################
#- alias: toilet_fan_on
#  initial_state: 'true'
#  trigger:
#    platform: event
#    event_type: xiaomi_aqara.click
#    event_data:
#      entity_id: binary_sensor.switch_158d0001b97111
#      click_type: double
#  action:
#  - service: switch.turn_on
#    entity_id: switch.plug_158d0001f54f91
#  - delay: 00:20:00
#  - service: switch.turn_off
#    entity_id: switch.plug_158d0001f54f91

# ##################################
# Toilet Fan - Off
# ##################################
- alias: toilet_fan_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b97111
        click_type: long_click_press
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.fan_t
  action:
    - service: switch.turn_off
      entity_id: switch.plug_158d0001f54f91
    - service: timer.cancel
      entity_id: timer.fan_t

# ##################################
# Toilet - Fan Timer start on
# ################################## 
- alias: toilet_fan_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.plug_158d0001f54f91
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.fan_t
    - service: timer.start
      entity_id: timer.fan_t

# ##################################
# Toilet - Timer restart with movement
# ################################## 
- alias: toilet_timer_restart
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id:  binary_sensor.motion_sensor_158d0001e54280
  condition:
    - condition: state
      entity_id: switch.wall_switch_left_158d0002a36f7f
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_t
    - service: timer.start
      entity_id: timer.main_light_t

# ##################################
# Toilet - Timer off
# ################################## 
- alias: toilet_timer_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.wall_switch_left_158d0002a36f7f
      to: 'off'
      from: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_t
    
# ##################################
# Toilet - Timer start
# ################################## 
- alias: toilet_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.wall_switch_left_158d0002a36f7f
      to: 'on'
      from: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_t
    - service: timer.start
      entity_id: timer.main_light_t

# ##################################
# Toilet - Timer pause on
# ################################## 
- alias: toilet_timer_pause_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0001e54280
  condition:
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d000232ddd6
      state: 'off'
    - condition: state
      entity_id: switch.wall_switch_left_158d0002a36f7f
      state: 'on'
  action:
    - service: timer.pause
      entity_id: timer.main_light_t
    - service: automation.turn_off
      entity_id: automation.toilet_timer_restart
    
# ##################################
# Bathroom - Timer pause off
# ################################## 
- alias: toilet_timer_pause_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000232ddd6
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.wall_switch_left_158d0002a36f7f
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.main_light_t
    - service: automation.turn_on
      entity_id: automation.toilet_timer_restart
    
# ##################################
# Toilet - Auto Light On
# ##################################
- alias: toilet_auto_light_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0001e54280
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b97111
        click_type: single
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000232ddd6
      to: 'off'
      from: 'on'
  condition:
    - condition: state
      entity_id: switch.wall_switch_left_158d0002a36f7f
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_left_158d0002a36f7f
    
# ##################################
# Toilet - Auto Light Off
# ##################################
- alias: toilet_auto_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.main_light_t
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_left_158d0002a36f7f

# ##################################
# Toilet - Auto Light off - No Motion 2m and Cover Closed
# ##################################
- alias: toilet_auto_light_off_no_motion_cover_closed
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e54280
      to: 'off'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d000232ddd6
        state: 'on'
      - condition: state
        entity_id: switch.wall_switch_left_158d0002a36f7f
        state: 'on'
  action:
    - service: timer.finish
      entity_id: timer.main_light_t


# ##################################
# Toilet - Water Leak Detected
# ##################################
- alias: toilet_water_leak_detected
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.water_leak_sensor_158d00023684c2
      from: 'off'
      to: 'on'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вним+ание! Обнар+ужена ут+ечка вод+ы в туал+ете! Обнар+ужена ут+ечка вод+ы в туал+ете! Вод+а перекрыв+ается!'
    - service: notify.telegram
      data_template:
        message: "\U000026d4 Внимание! Обнаружена утечка воды в туалете! Обнаружена утечка воды в туалете! Вода перекрывается!"
    - service: switch.turn_on
      entity_id: switch.plug_158d00020d8679
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.plug_158d00020d8679
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вод+а перекр+ыта! Устран+ите прот+ечку вод+ы в туал+ете дл+я включ+ения вод+ы!'
    - service: notify.telegram
      data_template:
        message: "\U000026d4 Внимание! Вода перекрыта! Устраните протечку воды в туалете для включения воды!"
    - service: notify.notify
      data:
        title: "Внимание!"
        message: "Сработал датчик протечки в туалете! Краны закрыты!"

# ##################################
# Toilet - Water Leak Off
# ##################################
- alias: toilet_water_leak_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.water_leak_sensor_158d00023684c2
      from: 'on'
      to: 'off'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Прот+ечка вод+ы в туал+ете устранен+а! Спас+ибо!'
    - service: notify.telegram
      data_template:
        message: "\U00002705 Протечка воды в туалете устранена!"
    
# ##################################
# Toilet - Light Toggle with Repeater
# ##################################
- alias: toilet_light_toggle_repeater
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d0001e0a622
  action:
    - service: switch.toggle
      entity_id: switch.wall_switch_left_158d0002a36f7f
