# #####################################################################################
#
# Water Counting
#
# #####################################################################################
# Cold Water - Increase
# ##################################
- alias: system_water_cold_water_increase_counter
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000232de79_contact
      from: 'on'
      to: 'off'
      for:
        seconds: 5
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.cold_water_meter
        value: "{{ (states('input_number.cold_water_meter')|float + 0.01 ) | round(2) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.cold_water_meter_month
        value: "{{ (states('input_number.cold_water_meter_month')|float + 0.01 ) | round(2) }}"

    - service: mqtt.publish
      data_template:
        topic: "utility/main/cold_water_meter"
        payload: "{{states('sensor.cold_water_meter')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/cold_water_meter_month"
        payload: "{{states('sensor.cold_water_meter_month')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/cold_water_meter_input"
        payload: "{{states('input_number.cold_water_meter')|float}}"
        retain: true
        

# ##################################
# Hot Water - Increase
# ##################################
- alias: system_water_hot_water_increase_counter
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000236fcd5_contact
      from: 'on'
      to: 'off'
      for:
        seconds: 5
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hot_water_meter
        value: "{{ (states('input_number.hot_water_meter')|float + 0.01 ) | round(2) }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hot_water_meter_month
        value: "{{ (states('input_number.hot_water_meter_month')|float + 0.01 ) | round(2) }}"

    - service: mqtt.publish
      data_template:
        topic: "utility/main/hot_water_meter"
        payload: "{{states('sensor.hot_water_meter')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/hot_water_meter_month"
        payload: "{{states('sensor.hot_water_meter_month')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/hot_water_meter_input"
        payload: "{{states('input_number.hot_water_meter')|float}}"
        retain: true

# ##################################
# System - Water\Power - Notification
# ##################################
- alias: system_new_month_notification
  initial_state: 'true'
  trigger:
    - platform: time
      at: '00:00:02'
  condition:
    - condition: template
      value_template: "{{ strptime(states('sensor.date'), '%Y-%m-%d').day|int == 21 }}"
  action:

    - service: input_number.set_value
      data_template:
        entity_id: input_number.power_meter_t1
        value: "{{ (states('sensor.power_meter_t1')) | float}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.power_meter_t2
        value: "{{ (states('sensor.power_meter_t2')) | float}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.cold_water_meter
        value: "{{ (states('sensor.cold_water_meter')) | float}}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hot_water_meter
        value: "{{ (states('sensor.hot_water_meter')) | float}}"
    
    - service: mqtt.publish
      data_template:
        topic: "utility/main/{{now().year}}/{{now().month}}/hot_water_meter"
        payload: "{{states('sensor.hot_water_meter')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/{{now().year}}/{{now().month}}/cold_water_meter"
        payload: "{{states('sensor.cold_water_meter')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/{{now().year}}/{{now().month}}/power_meter_t1"
        payload: "{{states('sensor.power_meter_t1')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/{{now().year}}/{{now().month}}/power_meter_t2"
        payload: "{{states('sensor.power_meter_t2')|float}}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "utility/main/{{now().year}}/{{now().month}}/timestamp"
        payload: "{{as_timestamp(now()) | timestamp_custom('%d-%m-%Y %H:%M:%S')}}"
        retain: true    

    - service: notify.telegram
      data_template: 
        message: >-
            {{ "\U0001f4a6" }}
            Холодная вода: {{ states('sensor.cold_water_meter')|float }}м3
            Горячая вода: {{ states('sensor.hot_water_meter')|float }}м3
            
            
            Расход за месяц:
            Холодная вода: {{ states('sensor.cold_water_meter')|float }}м3
            Горячая вода: {{ states('sensor.hot_water_meter')|float }}м3
            Стоимость: {{ ((states('sensor.water_cost'))|float)}}руб.

    - service: notify.telegram
      data_template: 
        message: >-
            {{ "\U0001f50c" }}
            Электричество (день) Т1: {{ ((states('sensor.power_t1'))|float)}} кВт*ч
            Электричество (ночь) Т2: {{ ((states('sensor.power_t2'))|float)}} кВт*ч
          
            
            Расход за месяц:
            Электричество (день) Т1: {{ ((states('sensor.power_consumption_month_t1'))|float)}} кВт*ч
            Электричество (ночь) Т2: {{ ((states('sensor.power_consumption_month_t2'))|float)}} кВт*ч
            Стоимость: {{ ((states('sensor.power_consumption_month_cost'))|float) }} руб.

    


# #####################################################################################
#
# Power Counting
#
# #####################################################################################
# System - Power - 30sec update
# ##################################
- alias: system_power_update_30s
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      seconds: '/30'
  action:
    - service: >
        {% if is_state('binary_sensor.tariff_t1','on') %}
            script.power_t1
        {% else %}
            script.power_t2
        {% endif %}
    - service: >
        {% if is_state('binary_sensor.tariff_t1','on') %}
            script.power_m_t1
        {% else %}
            script.power_m_t2
        {% endif %}
    # - service: mqtt.publish
    #   data:
    #     topic: "utility/main/power_t1"
    #     payload: "{{states('sensor.power_t1')|float}}"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: "utility/main/power_t2"
    #     payload: "{{states('sensor.power_t2')|float}}"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: "utility/main/power_consumption_month_t1"
    #     payload: "{{states('sensor.power_consumption_month_t1')|float}}"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: "utility/main/power_consumption_month_t2"
    #     payload: "{{states('sensor.power_consumption_month_t2')|float}}"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: "utility/main/power_t1_input"
    #     payload: "{{states('input_number.power_t1')|float}}"
    #     retain: true
    # - service: mqtt.publish
    #   data:
    #     topic: "utility/main/power_t2_input"
    #     payload: "{{states('input_number.power_t2')|float}}"
    #     retain: true

# ##################################
# System - Power - High current
# ##################################
- alias: system_power_15A_current
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.total_current
      above: 15
      below: 20
  action:
    - service: notify.telegram
      data:
        message: "\U0001f6a8 Внимание! Общий ток более 15А!"
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "Внимание! Общий ток более 15А"
  
# ##################################
# System - Power - High current
# ##################################
- alias: system_power_20A_current
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.total_current
      above: 20
      below: 30
  action:
    - service: notify.telegram
      data:
        message: "\U0001f6a8 Внимание! Общий ток более 20А!"
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "Внимание! Общий ток более 20А"
 
# ##################################
# System - Power - Ultra High current
# ##################################
- alias: system_power_30A_current
  initial_state: 'true'
  trigger:
    - platform: numeric_state
      entity_id: sensor.total_current
      above: 30
      below: 40
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Внимание! Общий ток более 30А!"
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "Внимание! Общий ток более 30А"
        

# ##################################
# System - Utility meter tariff change
# ##################################
- alias: system_power_tariff_change
  initial_state: 'true'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: '07:00:00'
    - platform: time
      at: '23:00:00'
  action:
    - service: utility_meter.select_tariff
      data_template:
        entity_id:
          - utility_meter.energy_monthly
          - utility_meter.energy_xiaomi_monthly
        tariff: "{%- if is_state('binary_sensor.tariff_t1','on') -%}day{%- else -%}night{%- endif -%}"
  
