# #####################################################################################
#
# VOVA
#
# #####################################################################################
# Vova Table Lamp (Yeelight Color E27) On
# ##################################
- alias: vova_table_lamp_on_if_lamp_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00016bdb4a
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00026eb820
        click_type: single
  condition:
    condition: state
    entity_id: light.led_color_v
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.led_color_v
    data_template:
      brightness_pct: 100
      kelvin: 5000
      
# ##################################
# Vova Table Lamp (Yeelight Color E27) Off
# ##################################
- alias: vova_table_lamp_off_if_lamp_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00016bdb4a
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00026eb820
        click_type: single
  condition:
    condition: state
    entity_id: light.led_color_v
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.led_color_v
    
# ##################################
# Vova Table Lamp (Yeelight Color E27) - Switch to Bright
# ##################################
- alias: vova_table_lamp_bright
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00016bdb4a
      click_type: double
  action:
    service: light.turn_on
    entity_id: light.led_color_v
    data_template:
      brightness_pct: 100
      kelvin: 5000
      
# ##################################
# Vova Table Lamp (Yeelight Color E27) - Switch to Mid-Night
# ##################################
- alias: vova_table_lamp_night
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00016bdb4a
      click_type: long_click_press
  action:
    service: light.turn_on
    entity_id: light.led_color_v
    data_template:
      brightness_pct: 5
      kelvin: 3000
      
# ##################################
# Vova Main Lamp (Xiaomi Sqaure LED) - On 100%\4500k
# ##################################
- alias: vova_main_lamp_on_if_lamp_off
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0001712d55
      click_type: single
  condition:
    condition: state
    entity_id: light.square_led_v
    state: 'off'
  action:
    service: light.turn_on
    entity_id: light.square_led_v
    data_template:
       brightness_pct: 95
       kelvin: 5000

# ##################################
# Vova Main Lamp (Xiaomi Sqaure LED) - Turn Plug On if Off
# ##################################
- alias: vova_main_lamp_plug_on_if_off
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0001712d55
      click_type: single
  condition:
    condition: state
    entity_id: switch.plug_158d00020b4971
    state: 'off'    
  action:
    service: switch.turn_on
    entity_id: switch.plug_158d00020b4971

# ##################################
# Vova Main Lamp (Xiaomi Sqaure LED) - Turn Plug On if Off
# ##################################
- alias: vova_main_lamp_plug_on_if_off
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_both_158d0001712d55
      click_type: both
  condition:
    - condition: state
      entity_id: light.square_led_v
      state: 'unavailable'
    - condition: state
      entity_id: switch.plug_158d00020b4971
      state: 'on'    
  action:
    service: switch.turn_off
    entity_id: switch.plug_158d00020b4971


# ##################################
# Vova Main Lamp (Xiaomi Sqaure LED) - On 5%\3000k
# ##################################
- alias: vova_main_lamp_on_5_if_lamp_off
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d0001712d55
      click_type: single
  condition:
    condition: state
    entity_id: light.square_led_v
    state: 'off'    
  action:
    service: light.turn_on
    entity_id: light.square_led_v
    data_template:
       brightness_pct: 5
       kelvin: 3000
       
# ##################################
# Vova Main Lamp (Xiaomi Sqaure LED) - Off if On
# ##################################
- alias: vova_main_lamp_off_if_lamp_on
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d0001712d55
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d0001712d55
        click_type: single
  condition:
    condition: state
    entity_id: light.square_led_v
    state: 'on'    
  action:
  - service: light.turn_off
    entity_id: light.square_led_v

# ##################################
# Vova Main Lamp (Xiaomi Sqaure LED) - Bed Switch
# ##################################
- alias: vova_main_lamp_with_bed_switch
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d00026eb820
      click_type: single
  action:
    service_template: >-
      {% if is_state('light.square_led_v','on') and (state_attr('light.square_led_v','brightness') < 100) %}
        script.square_lamp_to_100
      {% elif is_state('light.square_led_v','on') and (state_attr('light.square_led_v','brightness') > 230) %}
        script.square_lamp_off
      {% elif is_state('light.square_led_v','off') %}
        script.square_lamp_to_30
      {% endif %}
        
# ##################################
# Vova - Sockets On
# ##################################
- alias: vova_sockets_on
  initial_state: 'true'
  trigger:
    platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d000236bb94
  condition:
      - condition: state
        entity_id: switch.plug_158d000290a093
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.plug_158d000290a093
        - switch.plug_158d000290a0bc
        - switch.plug_158d000344998e
        - switch.plug_158d0003600ea4
    #- service: homeassistant.turn_on
    #  entity_id: automation.vova_iconbit_check

# ##################################
# Vova - Iconbit Off with TV Off
# ##################################
- alias: vova_iconbit_off_tv_off
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.tv_v
    to: 'off'
    for:
      minutes: 5
  condition:
      - condition: state
        entity_id: binary_sensor.iconbit_v
        state: 'on'
  action:
    - service: script.iconbit_toggle
    - delay: '00:00:10'
    - service: automation.turn_on
      entity_id: automation.vova_iconbit_reset

# ##################################
# Vova - Square LED Reset 
# ##################################
- alias: vova_square_led_reset
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: light.square_led_v
    to: 'unavailable'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day_long
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.square_led_restart

# ##################################
# Vova - Square LED status check
# ##################################
- alias: vova_square_led_status_check
  initial_state: 'true'
  trigger:
    platform: time
    at: '07:00:01'
  condition:
    condition: state
    entity_id: light.square_led_v
    state: 'unavailable'
  action:
    - service: script.turn_on
      entity_id: script.square_led_restart
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Square LED V restart done (morning)!"

# ##################################
# Vova - Square LED Power Switch Turn On
# ##################################
- alias: vova_square_led_switch_on
  initial_state: 'false'
  trigger:
    platform: state
    entity_id: switch.plug_158d00020b4971
    to: 'off'
    for:
      seconds: 3
  action:
    - service: switch.turn_on
      entity_id: switch.plug_158d00020b4971

# ##################################
# Vova - Bedside Lamp status check
# ##################################
- alias: vova_bedside_lamp_status_check
  initial_state: 'false'
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: state
    entity_id: light.bedside_mb
    state: 'unavailable'
  action:
    - service: script.turn_on
      entity_id: script.bedside_lamp_restart

# ##################################
# Vova - Bedside Lamp Reset 
# ##################################
- alias: vova_bedside_lamp_reset
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: light.bedside_mb
    to: 'unavailable'
    for:
      minutes: 5
  # condition:
  #   - condition: time
  #     after: '07:00:00'
  #     before: '23:00:00'
  action:
    - service: script.turn_on
      entity_id: script.bedside_lamp_restart

# ##################################
# Vova - Night mode
# ##################################
- alias: vova_night_mode
  initial_state: 'true'
  trigger:
    platform: time
    at: '23:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.plug_158d00028b4fc3, switch.wall_plug_158d000246776f
      
# ##################################
# Vova - Day mode
# ##################################
- alias: vova_day_mode
  initial_state: 'false'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      #- sat
      #- sun
  action:
    - service: homeassistant.turn_on
      entity_id: switch.plug_158d00028b4fc3 #, switch.wall_plug_158d000246776f

# ##################################
# Vova - Day mode - weekends
# ##################################
- alias: vova_day_mode_we
  initial_state: 'true'
  trigger:
    platform: time
    at: '10:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    - service: homeassistant.turn_on
      entity_id: switch.plug_158d00028b4fc3 #, switch.wall_plug_158d000246776f

# ##################################
# Vova - Breather Control
# ##################################
#- alias: vova_breather_control
#  initial_state: 'true'
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.door_window_sensor_158d00022ccffe
#      from: 'off'
#      to: 'on'
#    - platform: state
#      entity_id: binary_sensor.door_window_sensor_158d00022ccffe
#      from: 'on'
#      to: 'off'
#  condition:
#    - condition: template
#      value_template: "{{ states('binary_sensor.door_window_sensor_158d00022ccffe') == states('binary_sensor.breather_v') }}"
#  action:
#    - service: script.breather_toggle
#    - delay: '00:02:00'
#    - service_template: >
#        {% if states('binary_sensor.door_window_sensor_158d00022ccffe') == states('binary_sensor.breather_v') %}
#          script.breather_toggle
#        {% else %}
#          script.noop
#        {% endif %}