title: Security
icon: mdi:shield
show_header_toggle: false
cards:
  - type: vertical-stack
    cards:
      - type: glance
        title: Status
        entities:
          - entity: binary_sensor.security
            name: Security
            tap_action:
              action: call-service
              service: script.security_mode_toggle
          - entity: binary_sensor.family_home
            name: Family

      - type: entities
        #title: Safety
        show_header_toggle: false
        entities:
          - entity: sensor.security_last_change
            secondary_info: last-changed
            name: Last active sensor
          - type: divider
          - entity: binary_sensor.motion
            secondary_info: last-changed
          - entity: sensor.last_motion
            secondary_info: last-changed
          - type: divider
          - entity: binary_sensor.motion_unifi
            secondary_info: last-changed
          - type: divider
          - entity: binary_sensor.doors
            secondary_info: last-changed
          - entity: sensor.door_last_change
            secondary_info: last-changed
          - type: divider
          - entity: binary_sensor.windows
            secondary_info: last-changed
          - entity: sensor.window_last_change
            secondary_info: last-changed
            
      - type: entities
        #title: Fire Safety
        show_header_toggle: false
        entities:
          - entity: binary_sensor.natgas_sensor_158d00024bcf85
            secondary_info: last-changed
          - entity: binary_sensor.smoke_sensor_158d0002c92f31
            secondary_info: last-changed
  - type: vertical-stack
    cards:
      - type: entities
        title: Windows
        show_header_toggle: false
        entities:
          - entity: binary_sensor.door_window_sensor_158d00025371f6
            secondary_info: last-changed
          - entity: binary_sensor.door_window_sensor_158d000200ad58
            secondary_info: last-changed
          - entity: binary_sensor.door_window_sensor_158d00022ccffe
            secondary_info: last-changed
          - entity: binary_sensor.door_window_sensor_158d00025370d1
            secondary_info: last-changed
      
      - type: entities
        title: Doors
        show_header_toggle: false
        entities:
          - entity: binary_sensor.door_window_sensor_158d00027129ae
            secondary_info: last-changed
          - entity: binary_sensor.door_window_sensor_158d0001ef2ffc
            secondary_info: last-changed
          - entity: binary_sensor.door_window_sensor_158d0002a14c5e
            secondary_info: last-changed
          - entity: binary_sensor.door_window_sensor_158d0002529b9c
            secondary_info: last-changed
          - entity: binary_sensor.door_window_sensor_158d00025315e9
            secondary_info: last-changed
          - entity: binary_sensor.door_window_sensor_158d0001e5d6be
            secondary_info: last-changed
          - entity: binary_sensor.door_window_sensor_158d0002531749
            secondary_info: last-changed
  
  - type: entities
    title: Motion
    show_header_toggle: false
    entities:
      - entity: binary_sensor.motion_sensor_158d0001e53cda
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_158d000224f89f
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_158d000236bb94
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_158d0001e05856
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_158d0002b482e9
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_158d0001d5995e
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_158d0001ae9f61
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_158d0002b4729d
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_158d000236bc6d
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_158d0001e54280
        secondary_info: last-changed
      - entity: binary_sensor.motion_sensor_158d0001aea602
        secondary_info: last-changed
      - entity: binary_sensor.unifi_motion_entrance
        secondary_info: last-changed
      - entity: binary_sensor.unifi_motion_hall
        secondary_info: last-changed
      - entity: binary_sensor.unifi_motion_kitchen
        secondary_info: last-changed
      - entity: binary_sensor.unifi_motion_window
        secondary_info: last-changed
