# #####################################################################################
#
# HALL SMALL  - Lights
#
# #####################################################################################
# Hall Small - Auto Light On
# ##################################
- alias: hall_small_auto_night_light
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: xiaomi_aqara.motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0001ae9f61
      #from: 'off'
      #to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'off'
      - condition: state
        entity_id: switch.wall_switch_left_158d0002a36e26
        state: 'off'
      - condition: state
        entity_id: switch.plug_158d0001f5501f
        state: 'off'
      - condition: state
        entity_id: light.round_led_k
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: automation.kitchen_auto_night_light, switch.plug_158d0001f5501f
    - delay: '00:00:30'
    - service: switch.turn_off
      entity_id: switch.plug_158d0001f5501f
    - delay: '00:00:05'
    - service: switch.turn_off
      entity_id: switch.plug_158d0001f5501f
