# #####################################################################################
#
# HALL SMALL  - Lights
#
# #####################################################################################
# Hall Small - Auto Light On
# ##################################
- alias: hall_small_auto_night_light
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.motion
    #   event_data:
    #     entity_id: binary_sensor.motion_sensor_158d0001ae9f61
    - platform: state
      entity_id: binary_sensor.0x00158d0001ae9f61_occupancy
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.0x158d0003f27ce2_motion
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'off'
      - condition: state
        entity_id: switch.0x04cf8cdf3c7a9a48_switch_left #switch.0x00158d0002a36e26_switch_left #switch.wall_switch_left_158d0002a36e26
        state: 'off'
      - condition: state
        entity_id: light.btf_pixel_strip_top #switch.0x00158d0001f5501f_switch #switch.plug_158d0001f5501f
        state: 'off'
      - condition: state
        entity_id: light.round_led_k
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: automation.kitchen_auto_night_light #, switch.0x00158d0001f5501f_switch #switch.plug_158d0001f5501f
    - service: light.turn_on
      entity_id: light.btf_pixel_strip_top
      data:
        brightness_pct: 45
        rgb_color: [255, 180, 107] #255, 180, 107
    - delay: '00:00:30'
    - service: light.turn_off
      entity_id: light.btf_pixel_strip_top
    # - service: switch.turn_off
    #   entity_id: switch.0x00158d0001f5501f_switch #switch.plug_158d0001f5501f
    # - delay: '00:00:05'
    # - service: switch.turn_off
    #   entity_id: switch.0x00158d0001f5501f_switch #switch.plug_158d0001f5501f
