esphome:
  name: ble_gate
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Deliberant2"
  password: "123123123"
  manual_ip:
    static_ip: 192.168.0.114
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ble Gateway Fallback Hotspot"
    password: "Ao3sxnWOlM6c"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "1adamsik2"

ota:
  password: "1adamsik2"

# Веб сервер
web_server:
  port: 80

esp32_ble_tracker:

# # Наличие BLE устройств в зоне видимости
binary_sensor:
  - platform: ble_presence
    mac_address: EF:D0:88:58:9A:3B
    name: ${location}_mi_band_3_B

  - platform: ble_presence
    mac_address: CA:56:F0:5C:DB:C0
    name: ${location}_mi_band_3_M

  - platform: ble_presence
    mac_address: D2:F8:BD:98:B5:79
    name: ${location}_mi_band_4


sensor:
# Уровень сигнала обнаруженных устройств
  - platform: ble_rssi
    mac_address: EF:D0:88:58:9A:3B
    name: ${location}_mi_band_3_B_rssi

  - platform: ble_rssi
    mac_address: CA:56:F0:5C:DB:C0
    name: ${location}_mi_band_3_M_rssi


  - platform: ble_rssi
    mac_address: D2:F8:BD:98:B5:79
    name: ${location}_mi_band_4_rssi




# Датчики температуры и влажности
  - platform: xiaomi_lywsdcgq
    mac_address: A4:C1:38:F7:1C:39
    temperature:
      name: ${location}_bt_temperature
    humidity:
      name: ${location}_bt_humidity
    battery_level:
      name: ${location}_bt_battery_level


  - platform: xiaomi_lywsdcgq
    mac_address: A4:C1:38:CE:BD:AB
    temperature:
      name: ${location}_bt_temperature
    humidity:
      name: ${location}_bt_humidity
    battery_level:
      name: ${location}_bt_battery_level


  - platform: xiaomi_lywsdcgq
    mac_address: A4:C1:38:98:56:24
    temperature:
      name: ${location}_bt_temperature
    humidity:
      name: ${location}_bt_humidity
    battery_level:
      name: ${location}_bt_battery_level


  - platform: xiaomi_lywsdcgq
    mac_address: A4:C1:38:7F:74:24
    temperature:
      name: ${location}_bt_temperature
    humidity:
      name: ${location}_bt_humidity
    battery_level:
      name: ${location}_bt_battery_level

      
  - platform: xiaomi_lywsdcgq
    mac_address: A4:C1:38:5F:BC:A2
    temperature:
      name: ${location}_bt_temperature
    humidity:
      name: ${location}_bt_humidity
    battery_level:
      name: ${location}_bt_battery_level


# Время в онлайне
  - platform: uptime
    name: ${location}_esp32_uptime


# Уровень сигнала шлюза
  - platform: wifi_signal
    name:  ${location}_esp32_wi-fi
    update_interval: 60s

# Версия прошивки
text_sensor:
  - platform: version
    name: ${location}_esp32_firmware_version

# кнопка перезапуска    
switch:
  - platform: restart
    name: ${location}_esp32_Restart