esphome:
  name: bletracker
  platform: ESP32
  board: esp-wrover-kit

wifi:
  networks:
  - ssid: "DECK-A_2.4GHz"
    password: "Olympiys755"
  - ssid: "DECK-C_2.4GHz"
    password: "Olympiys755"
  - ssid: "OlyP_2.4"
    password: "OlyProspect_755"
  - ssid: "OlyP_2.4_plus"
    password: "OlyProspect_755"
  reboot_timeout: 0s
  manual_ip:
    static_ip: 192.168.10.253
    gateway: 192.168.10.1
    subnet: 255.255.255.0

  ap:
    ssid: "Monitor Fallback Hotspotble"
    password: "alex_alex"

logger:

api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80
  
binary_sensor:
  - platform: status
    name: ${board_name}_Status

esp32_ble_tracker:
  # scan_interval: 300s
 
sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:35:FE:EA
    temperature:
      name: "e_e_temperature"
    humidity:
      name: "e_e_humidity"
    battery_level:
      name: "e_e_battery"
switch:
  - platform: gpio
    pin: GPIO18
    name: "LED"

  - platform: restart
    name: ${board_name}_Restart