substitutions:
  board_name: d1_filter_flow

esphome:
  name: d1_filter_flow
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: .localdomain
  reboot_timeout: 0s
  output_power: 15dB
  manual_ip:
    static_ip: 192.168.1.112
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80
  
binary_sensor:
  - platform: status
    name: ${board_name}_Status
  
text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
      uint32_t dur = id(uptime_sensor).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start
    update_interval: 15s

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

  - platform: pulse_counter
    name: ${board_name}_Mineralized
    id: id_mineralized_pulse
    pin: D2
    update_interval: 15s
    unit_of_measurement: L
# 0.25 because of update_interval 15s 
    filters:
      - lambda: |-
          static float total_mineralized_value = 0.0;
          total_mineralized_value += x * 0.25 / 2145;
          return total_mineralized_value;         

  - platform: pulse_counter
    name: ${board_name}_NonMineralized
    id: id_nonmineralized_pulse
    pin: D3 # ==> D1
    update_interval: 15s
    unit_of_measurement: L
# 0.25 because of update_interval 15s 
    filters:
      - lambda: |-
          static float total_nonmineralized_value = 0.0;
          total_nonmineralized_value += x * 0.25 / 2145;
          return total_nonmineralized_value;

  - platform: pulse_counter
    name: ${board_name}_Raw
    id: id_raw_pulse
    pin: D5
    update_interval: 15s
    unit_of_measurement: L
# 0.25 because of update_interval 15s 
    filters:
      - lambda: |-
          static float total_raw_value = 0.0;
          total_raw_value += x * 0.25 / 2145;
          return total_raw_value;

  - platform: pulse_counter
    name: ${board_name}_PostMembrane
    id: id_postmembrane_pulse
    pin: D6
    update_interval: 15s
    unit_of_measurement: L
# 0.25 because of update_interval 15s 
    filters:
      - lambda: |-
          static float total_post_membrane_value = 0.0;
          total_post_membrane_value += x * 0.25 / 2145;
          return total_post_membrane_value;

switch:
  - platform: restart
    name: ${board_name}_Restart

time:
  - platform: homeassistant
    id: homeassistant_time