substitutions:
  board_name: d1_security

esphome:
  name: d1_security
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: .localdomain
  manual_ip:
    static_ip: 192.168.1.113
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80
  
binary_sensor:
  - platform: status
    name: ${board_name}_Status
    
  - platform: gpio
    pin: 
      number: D5
#     inverted: True
    name: ${board_name}_Alarm
  - platform: gpio
    pin: 
      number: D6
#      inverted: True
    name: ${board_name}_Armed
  - platform: gpio
    pin: 
      number: D7
#      inverted: True
    name: ${board_name}_Power

sensor:
  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s
  
  - platform: uptime
    name: ${board_name}_Uptime

switch:
  - platform: restart
    name: ${board_name}_Restart

time:
  - platform: homeassistant
    id: homeassistant_time