substitutions:
  board_name: d1mini_matrix
 
esphome:
  name: ${board_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: .localdomain
  reboot_timeout: 30min
  output_power: 17.5dB
  fast_connect: true
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.95
    gateway: 192.168.1.1
    subnet: 255.255.255.0

logger:

api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80
  
binary_sensor:
  - platform: status
    name: ${board_name}_Status

  - platform: homeassistant
    name: ${board_name}_HA_Matrix_Enable
    id: haonoff
    entity_id: input_boolean.matrix_enable

  - platform: homeassistant
    name: ${board_name}_HA_Matrix_Invert
    id: hainvert
    entity_id: input_boolean.matrix_invert
    
    
spi:
  clk_pin: D5  # D5 is connected to CLK of MAX7219
  mosi_pin: D7 # D7 is connected to MOSI of MAX7219

display:
  - platform: max7219digit
    cs_pin: D8 # D8 is connected to CS of MAX7219
    num_chips: 8
    intensity: 3
    update_interval: 100ms
    lambda: |-
      it.printf(0, 0, id(digit_font), TextAlign::TOP_LEFT, "%s", id(hatxt).state.c_str());
      it.intensity(id(habri).state);
      it.scroll(true, 0, id(haspeed).state, 1, 1);
      it.turn_on_off(id(haonoff).state);
      it.invert_on_off(id(hainvert).state);

#it.scroll_left();

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
      uint32_t dur = id(uptime_sensor).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start
    update_interval: 15s

  - platform: homeassistant
    name: ${board_name}_HA_TXT
    id: hatxt
    entity_id: input_text.matrix_text

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

  - platform: adc
    id: adc_val
    pin: A0 # A photoresistor is connected to 3.3V and A0, A0 is connected to GND with 10k resistor
    name: ${board_name}_Display_Brightness
    update_interval: 60s
    unit_of_measurement: "adc"
    filters:
      - multiply: 3.3
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.3 -> 15

  - platform: homeassistant
    name: ${board_name}_HA_Brightness
    id: habri
    entity_id: input_number.matrix_brightness

  - platform: homeassistant
    name: ${board_name}_HA_Speed
    id: haspeed
    entity_id: input_number.matrix_speed


switch:
  - platform: restart
    name: ${board_name}_Restart

time:
  - platform: homeassistant
    id: homeassistant_time

font:
  - file: "pixelmix.ttf"
    id: digit_font
    size: 8
    glyphs:
    - ' '
    - '@'
    - '*'
    - '!'
    - '"'
    - '%'
    - (
    - )
    - +
    - ','
    - '-'
    - .
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - ':'
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R
    - S
    - T
    - U
    - V
    - W
    - X
    - Y
    - Z
    - _
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - n
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - y
    - z
    - °