substitutions:
  board_name: esp32_domofon

esphome:
  name: esp32_domofon
  platform: ESP32
  board: lolin32

wifi:
  ssid: !secret wifi_ssid_hb
  password: !secret wifi_pass
  domain: .localdomain
  reboot_timeout: 10min
  output_power: 17.5dB
  fast_connect: true
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.101
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80

  
binary_sensor:
  - platform: status
    name: ${board_name}_Status

  # - platform: gpio
  #   pin: 
  #     number: GPIO12 # TO GPIO13
  #     inverted: true
  #   name: ${board_name}_Meter_Imp
  #   filters:
  #     - delayed_on: 15ms
  #     - delayed_off: 15ms
    
  - platform: gpio
    pin:
      number: GPIO32
      inverted: false
    name: ${board_name}_Motion
    device_class: motion

  - platform: gpio
    pin: 
      number: GPIO21
#      inverted: true
#      mode: INPUT_PULLUP
    name: ${board_name}_IncomingCall
    device_class: sound
    filters:
      - delayed_off: 2500ms

    
  # - platform: template
  #   name: ${board_name}_IncomingCall
  #   device_class: sound
  #   lambda: |-
  #     if (id(speakervoltage).state > 1.5) {
  #       // Voltage >1.5v
  #       return true;
  #     } else {
  #       // Valtage <1.5v
  #       return false;
  #     }
  #   filters:
  #     delayed_off: 3000ms
  
text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
      uint32_t dur = id(uptime_sensor).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start
    update_interval: 15s

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

  # - platform: adc
  #   pin: GPIO32 #A0 #GPIO34
  #   name: ${board_name}_PIR_V
  #   update_interval: 1s
  #   attenuation: 11db
    
  # - platform: adc
  #   pin: GPIO34 #A0 #GPIO34
  #   name: ${board_name}_SpeakerVoltage
  #   update_interval: 1s
  #   internal: true
  #   id: speakervoltage
  #   filters:
  #     - multiply: 10

  - platform: pulse_counter
    pin: GPIO12 # TO GPIO13
    unit_of_measurement: 'W'
    update_interval: 10s
    name: ${board_name}_Power_Meter
    filters:
      - multiply: 12 #0.012
    internal_filter: 10us
    accuracy_decimals: 0
#    internal_filter: 10000us

switch:
  - platform: restart
    name: ${board_name}_Restart
  
  - platform: gpio
    pin: 
      number: GPIO19
      inverted: yes
    name: ${board_name}_Relay1
    id: relay1
    icon: mdi:phone
  - platform: gpio
    pin: 
      number: GPIO18
      inverted: yes
    name: ${board_name}_Relay2
    id: relay2
    icon: mdi:phone
  - platform: gpio
    pin: 
      number: GPIO17
      inverted: yes
    name: ${board_name}_Relay3
    id: relay3
    icon: mdi:door-open

  - platform: gpio
    pin: 
      number: GPIO16
      inverted: yes
    name: ${board_name}_Relay4
    id: relay4
    icon: mdi:volume-off

  - platform: template
    name: ${board_name}_OpenDoor
    icon: mdi:door-open
    turn_on_action:
    - switch.turn_on: relay3
    - delay: 2s
    - switch.turn_off: relay3
  
  - platform: template
    name: ${board_name}_Phone
    icon: mdi:phone
    lambda: |-
      if (id(relay1).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: relay1
      - switch.turn_on: relay2
    turn_off_action:
      - switch.turn_off: relay1
      - switch.turn_off: relay2


output:
  - platform: ledc
    pin: GPIO25
    id: yellow_led
  
  - platform: ledc
    pin: GPIO26
    id: green_led
    
  - platform: ledc
    pin: GPIO27
    id: blue_led
    
  - platform: ledc
    pin: GPIO14 # top GPIO33
    id: red_led
  
# Example usage in a light
light:
  - platform: monochromatic
    output: yellow_led
    name: ${board_name}_yellow_led
    default_transition_length: 50ms
    id: light_yellow_led
    effects:
      - automation:
          name: "Blink"
          sequence:
            - light.turn_on:
                id: light_yellow_led
                brightness: 50%
                transition_length: 500ms
            - delay: 1000ms
            - light.turn_on:
                id: light_yellow_led
                brightness: 1%
                transition_length: 300ms
            - delay: 500ms
      - automation:
          name: "Blink Fast"
          sequence:
            - light.turn_on:
                id: light_yellow_led
                brightness: 50%
                transition_length: 50ms
            - delay: 450ms
            - light.turn_on:
                id: light_yellow_led
                brightness: 1%
                transition_length: 50ms
            - delay: 450ms
      - automation:
          name: "Half"
          sequence:
            - light.turn_on:
                id: light_yellow_led
                brightness: 50%
                transition_length: 50ms

  - platform: monochromatic
    output: green_led
    name: ${board_name}_green_led
    default_transition_length: 50ms
    id: light_green_led
    effects:
      - automation:
          name: "Blink"
          sequence:
            - light.turn_on:
                id: light_green_led
                brightness: 100%
                transition_length: 50ms
            - delay: 200ms
            - light.turn_on:
                id: light_green_led
                brightness: 0%
                transition_length: 50ms
            - delay: 200ms
      - automation:
          name: "Blink Fast"
          sequence:
            - light.turn_on:
                id: light_green_led
                brightness: 50%
                transition_length: 50ms
            - delay: 450ms
            - light.turn_on:
                id: light_green_led
                brightness: 1%
                transition_length: 50ms
            - delay: 450ms
      - automation:
          name: "Half"
          sequence:
            - light.turn_on:
                id: light_green_led
                brightness: 50%
                transition_length: 50ms

  - platform: monochromatic
    output: blue_led
    name: ${board_name}_blue_led
    default_transition_length: 50ms
    id: light_blue_led
    effects:
      - automation:
          name: "Blink"
          sequence:
            - light.turn_on:
                id: light_blue_led
                brightness: 50%
                transition_length: 500ms
            - delay: 1000ms
            - light.turn_on:
                id: light_blue_led
                brightness: 1%
                transition_length: 300ms
            - delay: 500ms
      - automation:
          name: "Blink Fast"
          sequence:
            - light.turn_on:
                id: light_blue_led
                brightness: 50%
                transition_length: 50ms
            - delay: 450ms
            - light.turn_on:
                id: light_blue_led
                brightness: 1%
                transition_length: 50ms
            - delay: 450ms
      - automation:
          name: "Half"
          sequence:
            - light.turn_on:
                id: light_blue_led
                brightness: 50%
                transition_length: 50ms

  - platform: monochromatic
    output: red_led
    name: ${board_name}_red_led
    default_transition_length: 50ms
    id: light_red_led
    effects:
      - automation:
          name: "Blink"
          sequence:
            - light.turn_on:
                id: light_red_led
                brightness: 50%
                transition_length: 500ms
            - delay: 1000ms
            - light.turn_on:
                id: light_red_led
                brightness: 1%
                transition_length: 300ms
            - delay: 500ms
      - automation:
          name: "Blink Fast"
          sequence:
            - light.turn_on:
                id: light_red_led
                brightness: 50%
                transition_length: 50ms
            - delay: 450ms
            - light.turn_on:
                id: light_red_led
                brightness: 1%
                transition_length: 50ms
            - delay: 450ms
      - automation:
          name: "Half"
          sequence:
            - light.turn_on:
                id: light_red_led
                brightness: 50%
                transition_length: 50ms


time:
  - platform: homeassistant
    id: homeassistant_time