substitutions:
  board_name: esp32_laser_test

esphome:
  name: ${board_name}
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: .localdomain
  reboot_timeout: 0s
  manual_ip:
    static_ip: 192.168.1.247
    gateway: 192.168.1.1
    subnet: 255.255.255.0

logger:

api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: True
  - id: bus_b
    sda: GPIO2
    scl: GPIO15
    scan: True
    
  

binary_sensor:
  - platform: status
    name: ${board_name}_Status
    
  - platform: gpio
    pin: GPIO32
    name: g32_test

  - platform: gpio
    pin: GPIO35
    name: g35_test

  - platform: gpio
    pin: GPIO34
    name: g34_test

  - platform: gpio
    pin: GPIO33
    name: g33_test
  

sensor:
  - platform: uptime
    name: ${board_name}_Uptime
    id: uptime_sensor
    update_interval: 15s
    
  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s
    
  - platform: vl53l0x
    i2c_id: bus_a
    name: ${board_name}_Dist_a
    update_interval: 2s
    address: 0x29
    unit_of_measurement: "cm"
    filters:
      - multiply: 100

  - platform: vl53l0x
    i2c_id: bus_b
    name: ${board_name}_Dist_b
    update_interval: 2s
    address: 0x29
    unit_of_measurement: "cm"
    filters:
      - multiply: 100

    
switch:
  - platform: restart
    name: ${board_name}_Restart

time:
  - platform: homeassistant
    id: homeassistant_time