substitutions:
  board_name: monitor


esphome:
  name: ${board_name}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "OlyEngine"
  password: ""
  reboot_timeout: 0s
  manual_ip:
    static_ip: 192.168.10.254
    gateway: 192.168.10.1
    subnet: 255.255.255.0

  ap:
    ssid: "Monitor Fallback Hotspot"
    password: "alex_alex"

logger:

api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80
  
binary_sensor:
#  - platform: status
#    name: ${board_name}_Status

  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: 440V_MSB
    filters:
      - delayed_on: 20ms
      - delayed_off: 5000ms

  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    name: 220V_MSB
    filters:
      - delayed_on: 20ms
      - delayed_off: 5000ms

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: 220V_ESB
    filters:
      - delayed_on: 20ms
      - delayed_off: 5000ms

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: L-7
    filters:
      - delayed_on: 20ms
      - delayed_off: 5000ms

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
      uint32_t dur = id(uptime_sensor).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start
    update_interval: 15s

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    internal: true
    update_interval: 15s
    
#  - platform: wifi_signal
#    name: ${board_name}_WiFi_RSSI
#    update_interval: 60s


#switch:
#  - platform: restart
#    name: ${board_name}_Restart