substitutions:
  board_name: sonoff_basic_2

esphome:
  name: sonoff_basic_2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: .localdomain
  manual_ip:
    static_ip: 192.168.1.130
    gateway: 192.168.1.1
    subnet: 255.255.255.0

api:
  reboot_timeout: 0s

logger:

ota:

#dallas:
#  pin: GPIO02

web_server:
  port: 80

status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${board_name}_Button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: ${board_name}_Status

switch:
  - platform: gpio
    name: ${board_name}_Relay
    pin: GPIO12
    id: relay

sensor:
  - platform: uptime
    name: ${board_name}_uptime

  - platform: wifi_signal
    name: ${board_name}_wifi_signal
    update_interval: 60s

time:
  - platform: homeassistant
    id: homeassistant_time