esphome:
  name: test
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "1"
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "32CwBmmJ6dDK"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

output:
  - platform: gpio
    id: my_pin
    pin:
      number: GPIO03
      inverted: True
      mode: INPUT_PULLUP
      
light:
  - platform: binary
    name: "Desk Lamp"
    output: my_pin     