- platform: yandex_covid

- platform: template
  sensors:
    covid_russia_cases:
      friendly_name: Russia Confirmed
      icon_template: mdi:emoticon-neutral-outline
      unit_of_measurement: people
      value_template: "{{ state_attr('sensor.yandex_covid', 'Россия')['cases'] }}"
    covid_russia_cured:
      friendly_name: Russia Recovered
      icon_template: mdi:emoticon-happy-outline
      unit_of_measurement: people
      value_template: "{{ state_attr('sensor.yandex_covid', 'Россия')['cured'] }}"
    covid_russia_deaths:
      friendly_name: Russia Deaths
      icon_template: mdi:emoticon-dead-outline
      unit_of_measurement: people
      value_template: "{{ state_attr('sensor.yandex_covid', 'Россия')['deaths'] }}"
    covid_russia_new_cases:
      friendly_name: Russia New Cases
      icon_template: mdi:emoticon-cry-outline
      unit_of_measurement: people
      value_template: "{{ state_attr('sensor.yandex_covid', 'Россия')['new_cases'] }}"
    covid_russia_tests:
      friendly_name: Russia Tests
      icon_template: mdi:test-tube
      unit_of_measurement: people
      value_template: "{{ state_attr('sensor.yandex_covid', 'Россия')['tests'] }}"

    covid_moscow_cases:
      friendly_name: Moscow Confirmed
      icon_template: mdi:emoticon-neutral-outline
      unit_of_measurement: people
      value_template: "{{ state_attr('sensor.yandex_covid', 'Москва')['cases'] }}"
    covid_moscow_cured:
      friendly_name: Moscow Recovered
      icon_template: mdi:emoticon-happy-outline
      unit_of_measurement: people
      value_template: "{{ state_attr('sensor.yandex_covid', 'Москва')['cured'] }}"
    covid_moscow_deaths:
      friendly_name: Moscow Deaths
      icon_template: mdi:emoticon-dead-outline
      unit_of_measurement: people
      value_template: "{{ state_attr('sensor.yandex_covid', 'Москва')['deaths'] }}"